/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: bc2da6b8-d73c-4f53-9700-f62675aeb131

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We have verified the properties of the DULA spectral operator on the compact domain L²([0,L]).
Specifically, we have proved:
1. The kernel is symmetric, continuous, and bounded.
2. The operator H_DULA_compact is self-adjoint on L²([0,L]).
3. The operator is bounded on L²([0,L]).
4. The operator has finite rank, and its spectrum is a nonempty finite set.
5. We have formalized the statements of Direction A and Direction B regarding the asymptotic behavior of the spectrum.
All proofs are complete.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open MeasureTheory


def chi6 (n : ℤ) : ℝ :=
  if n % 6 = 1 then 1
  else if n % 6 = 5 then -1
  else 0

lemma chi6_one : chi6 1 = 1 := by
  -- By definition of Dirichlet characters, we know that χ(1) = 1.
  simp [chi6] at *
lemma chi6_five : chi6 5 = -1 := by
  -- By definition of chi6, we know that chi6(5) = -1.
  simp +decide [chi6] at *
lemma chi6_two : chi6 2 = 0 := by
  -- By definition of chi6, we know that chi6(2) = 0.
  simp [chi6]
lemma chi6_three : chi6 3 = 0 := by
  -- By definition of $chi6$, we know that $chi6(3) = 0$ because $3$ is not coprime to $6$.
  simp [chi6] at *

lemma chi6_periodic (n : ℤ) : chi6 (n + 6) = chi6 n := by
  -- By definition of $chi6$, we know that $chi6(n) = 1$ if $n$ is odd and $chi6(n) = 0$ if $n$ is even.
  simp [chi6] at *

lemma chi6_abs_le_one (n : ℤ) : |chi6 n| ≤ 1 := by
  -- By definition of $chi6$, we know that $|chi6 n| \leq 1$ for all $n$. This follows from the fact that $chi6$ is a Dirichlet character modulo 6.
  have h_abs : ∀ n : ℤ, |chi6 n| ≤ 1 := by
    intro n
    have h_cases : chi6 n = 0 ∨ chi6 n = 1 ∨ chi6 n = -1 := by
      by_cases h : n % 6 = 1 ∨ n % 6 = 5 <;> simp +decide [ chi6, h ];
      · grind +ring;
      · grind
    rcases h_cases with ( h | h | h ) <;> norm_num [ h ]
  exact h_abs n

def primes_mod6 (N : ℕ) : Finset ℕ :=
  (Finset.range N).filter (fun p => Nat.Prime p ∧ (p % 6 = 1 ∨ p % 6 = 5))

lemma primes_mod6_log_pos (N : ℕ) (p : ℕ) (hp : p ∈ primes_mod6 N) :
    Real.log p > 0 := by
  have hprime := (Finset.mem_filter.mp hp).2.1
  exact Real.log_pos (by exact_mod_cast Nat.Prime.one_lt hprime)

noncomputable def DULA_kernel (N : ℕ) (x y : ℝ) : ℝ :=
  ∑ p ∈ primes_mod6 N,
    chi6 p * (Real.log p / Real.sqrt p) * Real.cos (Real.log p * (x - y))

theorem DULA_kernel_symmetric (N : ℕ) (x y : ℝ) :
    DULA_kernel N x y = DULA_kernel N y x := by
      -- Since cosine is an even function, we have $\cos(-θ) = \cos(θ)$ for any angle $θ$, so the two sums are equal.
      apply Finset.sum_congr rfl
      intro p hp
      rw [← Real.cos_neg]
      ring

theorem DULA_kernel_continuous (N : ℕ) :
    Continuous (fun p : ℝ × ℝ => DULA_kernel N p.1 p.2) := by
      -- The sum of continuous functions is continuous, so the entire sum is continuous.
      apply continuous_finset_sum; intro p_1 hp_1; exact Continuous.mul (continuous_const) (Real.continuous_cos.comp (by continuity))

theorem DULA_kernel_bounded (N : ℕ) :
    ∃ C : ℝ, ∀ x y : ℝ, |DULA_kernel N x y| ≤ C := by
      use 6 * N;
      intro x y;
      refine' le_trans ( Finset.abs_sum_le_sum_abs _ _ ) _;
      refine' le_trans ( Finset.sum_le_sum fun i hi => _ ) _;
      use fun i => Real.log i / Real.sqrt i;
      · rw [ abs_mul, abs_mul, abs_of_nonneg ( show 0 ≤ Real.log i / Real.sqrt i by positivity ) ];
        exact le_trans ( mul_le_of_le_one_right ( by positivity ) ( Real.abs_cos_le_one _ ) ) ( mul_le_of_le_one_left ( by positivity ) ( show |chi6 i| ≤ 1 by exact chi6_abs_le_one i ) );
      · refine' le_trans ( Finset.sum_le_sum fun i hi => div_le_one_of_le₀ ( show Real.log i ≤ Real.sqrt i from _ ) ( Real.sqrt_nonneg _ ) ) _;
        · have := Real.log_le_sub_one_of_pos ( show 0 < Real.sqrt i / 2 by exact div_pos ( Real.sqrt_pos.mpr ( Nat.cast_pos.mpr ( Nat.Prime.pos ( by unfold primes_mod6 at hi; aesop ) ) ) ) zero_lt_two );
          rw [ Real.log_div ( by exact ne_of_gt <| Real.sqrt_pos.mpr <| Nat.cast_pos.mpr <| Nat.Prime.pos <| by unfold primes_mod6 at hi; aesop ) ( by norm_num ), Real.log_sqrt <| Nat.cast_nonneg _ ] at this ; linarith [ Real.log_le_sub_one_of_pos zero_lt_two ];
        · norm_num +zetaDelta at *;
          exact_mod_cast le_trans ( Finset.card_filter_le _ _ ) ( by norm_num; linarith )

noncomputable def H_DULA_compact (L : ℝ) (N : ℕ) (f : ℝ → ℝ) : ℝ → ℝ :=
  fun x => ∫ y in Set.Icc 0 L, DULA_kernel N x y * f y

theorem H_DULA_compact_expansion (L : ℝ) (N : ℕ) (f : ℝ → ℝ)
    (hf : MeasureTheory.Integrable f (MeasureTheory.Measure.restrict volume (Set.Icc 0 L))) :
    ∀ x, H_DULA_compact L N f x =
      ∑ p ∈ primes_mod6 N,
        chi6 p * (Real.log p / Real.sqrt p) *
          ((∫ y in Set.Icc 0 L, Real.cos (Real.log p * y) * f y) *
            Real.cos (Real.log p * x) +
           (∫ y in Set.Icc 0 L, Real.sin (Real.log p * y) * f y) *
            Real.sin (Real.log p * x)) := by
              -- By definition of $H_DULA_compact$, we can write it as an integral of the kernel times $f(y)$.
              have h_integral : ∀ x, H_DULA_compact L N f x = ∫ y in Set.Icc 0 L, (∑ p ∈ primes_mod6 N, chi6 p * (Real.log p / Real.sqrt p) * Real.cos (Real.log p * (x - y))) * f y := by
                exact?;
              intro x
              rw [h_integral];
              simp +decide only [mul_comm, mul_left_comm, Finset.mul_sum _ _ _,
                                ← integral_const_mul];
              rw [ MeasureTheory.integral_finset_sum ];
              · refine' Finset.sum_congr rfl fun p hp => _;
                rw [ ← MeasureTheory.integral_add ];
                · rw [ ← MeasureTheory.integral_const_mul ] ; congr ; ext y ; rw [ sub_mul ] ; rw [ Real.cos_sub ] ; ring;
                · refine' hf.norm.mono' _ _;
                  · exact hf.1.mul ( Continuous.aestronglyMeasurable ( by continuity ) );
                  · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Icc ] with y hy using by rw [ norm_mul ] ; exact mul_le_of_le_one_right ( norm_nonneg _ ) ( by rw [ norm_mul ] ; exact mul_le_one₀ ( Real.abs_cos_le_one _ ) ( abs_nonneg _ ) ( Real.abs_cos_le_one _ ) ) ;
                · refine' hf.norm.mono' _ _;
                  · exact hf.1.mul ( Continuous.aestronglyMeasurable ( by exact Continuous.mul ( continuous_const ) ( Real.continuous_sin.comp ( by continuity ) ) ) );
                  · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Icc ] with y hy using by rw [ norm_mul ] ; exact mul_le_of_le_one_right ( norm_nonneg _ ) ( by rw [ norm_mul ] ; exact mul_le_one₀ ( Real.abs_sin_le_one _ ) ( abs_nonneg _ ) ( Real.abs_sin_le_one _ ) ) ;
              · intro p hp; refine' MeasureTheory.Integrable.mono' _ _ _;
                refine' fun y => |f y| * ( |chi6 p| * ( |Real.log p| / Real.sqrt p ) );
                · exact MeasureTheory.Integrable.mul_const ( hf.norm ) _;
                · fun_prop;
                · simp [abs_mul];
                  exact Filter.eventually_inf_principal.mpr ( Filter.Eventually.of_forall fun y hy => mul_le_mul_of_nonneg_left ( mul_le_mul_of_nonneg_left ( mul_le_of_le_one_left ( by positivity ) ( Real.abs_cos_le_one _ ) |> le_trans <| by rw [ abs_of_nonneg ( Real.sqrt_nonneg _ ) ] ) <| by positivity ) <| by positivity )

theorem H_DULA_compact_selfadjoint (L : ℝ) (N : ℕ) (f g : ℝ → ℝ)
    (hf : MeasureTheory.Integrable f (MeasureTheory.Measure.restrict volume (Set.Icc 0 L)))
    (hg : MeasureTheory.Integrable g (MeasureTheory.Measure.restrict volume (Set.Icc 0 L))) :
    ∫ x in Set.Icc 0 L, H_DULA_compact L N f x * g x =
    ∫ x in Set.Icc 0 L, f x * H_DULA_compact L N g x := by
      -- By Fubini's theorem, we can interchange the order of integration.
      have h_fubini : ∫ x in Set.Icc 0 L, ∫ y in Set.Icc 0 L, DULA_kernel N x y * f y * g x = ∫ y in Set.Icc 0 L, ∫ x in Set.Icc 0 L, DULA_kernel N x y * f y * g x := by
        -- Apply Fubini's theorem to interchange the order of integration.
        have h_fubini : MeasureTheory.IntegrableOn (fun p : ℝ × ℝ => DULA_kernel N p.1 p.2 * f p.2 * g p.1) (Set.Icc 0 L ×ˢ Set.Icc 0 L) := by
          -- Since $DULA_kernel N$ is continuous and $f$ and $g$ are integrable, their product is integrable.
          have h_cont : ContinuousOn (fun p : ℝ × ℝ => DULA_kernel N p.1 p.2) (Set.Icc 0 L ×ˢ Set.Icc 0 L) := by
            exact Continuous.continuousOn ( DULA_kernel_continuous N );
          have h_integrable : MeasureTheory.IntegrableOn (fun p : ℝ × ℝ => f p.2 * g p.1) (Set.Icc 0 L ×ˢ Set.Icc 0 L) := by
            have h_integrable : MeasureTheory.IntegrableOn (fun p : ℝ × ℝ => g p.1 * f p.2) (Set.Icc 0 L ×ˢ Set.Icc 0 L) := by
              have h_prod_integrable : MeasureTheory.Integrable (fun p : ℝ × ℝ => g p.1 * f p.2) (MeasureTheory.Measure.prod (MeasureTheory.Measure.restrict MeasureTheory.volume (Set.Icc 0 L)) (MeasureTheory.Measure.restrict MeasureTheory.volume (Set.Icc 0 L))) := by
                exact MeasureTheory.Integrable.mul_prod hg hf
              rw [ MeasureTheory.Measure.prod_restrict ] at h_prod_integrable ; aesop;
            simpa only [ mul_comm ] using h_integrable;
          refine' MeasureTheory.Integrable.mono' _ _ _;
          refine' fun p => ( SupSet.sSup ( Set.image ( fun p : ℝ × ℝ => |DULA_kernel N p.1 p.2| ) ( Set.Icc 0 L ×ˢ Set.Icc 0 L ) ) ) * |f p.2 * g p.1|;
          · exact MeasureTheory.Integrable.const_mul ( h_integrable.norm ) _;
          · simpa only [ mul_assoc ] using MeasureTheory.AEStronglyMeasurable.mul ( h_cont.aestronglyMeasurable ( measurableSet_Icc.prod measurableSet_Icc ) ) h_integrable.aestronglyMeasurable;
          · filter_upwards [ MeasureTheory.ae_restrict_mem ( measurableSet_Icc.prod measurableSet_Icc ) ] with p hp using by simpa [ abs_mul, mul_assoc ] using mul_le_mul_of_nonneg_right ( le_csSup ( IsCompact.bddAbove ( isCompact_Icc.prod CompactIccSpace.isCompact_Icc |> IsCompact.image_of_continuousOn <| continuous_abs.comp_continuousOn h_cont ) ) <| Set.mem_image_of_mem _ hp ) <| by positivity;
        rw [ MeasureTheory.integral_integral_swap ];
        simpa only [ MeasureTheory.Measure.prod_restrict ] using h_fubini;
      convert h_fubini using 1 ; unfold H_DULA_compact ; simp +decide [ mul_assoc, mul_comm, mul_left_comm, ← MeasureTheory.integral_const_mul ] ; ring;
      unfold H_DULA_compact; simp +decide [ mul_assoc, mul_comm, mul_left_comm, ← MeasureTheory.integral_const_mul ] ; ring;
      exact MeasureTheory.setIntegral_congr_fun measurableSet_Icc fun x hx => MeasureTheory.setIntegral_congr_fun measurableSet_Icc fun y hy => by rw [ DULA_kernel_symmetric ] ;

noncomputable def spectrum_DULA_compact (L : ℝ) (N : ℕ) : Set ℝ :=
  { μ | ∃ ψ : ℝ → ℝ,
      MeasureTheory.MemLp ψ 2 (MeasureTheory.Measure.restrict volume (Set.Icc 0 L)) ∧
      (∀ x ∈ Set.Icc 0 L, H_DULA_compact L N ψ x = μ * ψ x) ∧
      ¬ (ψ =ᵐ[MeasureTheory.Measure.restrict volume (Set.Icc 0 L)] 0) }

def DULA_basis_functions (N : ℕ) : Finset (ℝ → ℝ) :=
  (primes_mod6 N).image (fun p => (fun x => Real.cos (Real.log p * x))) ∪
  (primes_mod6 N).image (fun p => (fun x => Real.sin (Real.log p * x)))

def Direction_A_asymptotic : Prop :=
  ∀ (γ : ℝ) (ε : ℝ), ε > 0 →
    riemannZeta (1/2 + Complex.I * γ) = 0 → γ > 0 →
    ∃ N L : ℕ, (0 : ℝ) < L ∧
      ∃ μ ∈ spectrum_DULA_compact L N,
        |μ - γ| < ε

def Direction_B_asymptotic : Prop :=
  ∀ (μ : ℝ) (ε : ℝ), ε > 0 →
    (∃ N L : ℕ, (0 : ℝ) < L ∧ μ ∈ spectrum_DULA_compact L N) →
    ∃ γ : ℝ, riemannZeta (1/2 + Complex.I * γ) = 0 ∧ γ > 0 ∧ |μ - γ| < ε

/-
The range of H_DULA_compact is contained in the finite-dimensional span of DULA_basis_functions.
-/
theorem H_DULA_compact_range_subset_span (L : ℝ) (N : ℕ) (f : ℝ → ℝ)
    (hf : MeasureTheory.Integrable f (MeasureTheory.Measure.restrict volume (Set.Icc 0 L))) :
    H_DULA_compact L N f ∈ Submodule.span ℝ (DULA_basis_functions N : Set (ℝ → ℝ)) := by
      have h_expansion : ∀ x, H_DULA_compact L N f x = ∑ p ∈ primes_mod6 N, (chi6 p) * (Real.log p / Real.sqrt p) * ((∫ y in Set.Icc 0 L, Real.cos (Real.log p * y) * f y) * Real.cos (Real.log p * x) + (∫ y in Set.Icc 0 L, Real.sin (Real.log p * y) * f y) * Real.sin (Real.log p * x)) := by
        exact?;
      -- By definition of $DULA_basis_functions$, each term in the sum is in the span of $DULA_basis_functions$.
      have h_term_in_span : ∀ p ∈ primes_mod6 N, (fun x => Real.cos (Real.log p * x)) ∈ DULA_basis_functions N ∧ (fun x => Real.sin (Real.log p * x)) ∈ DULA_basis_functions N := by
        unfold DULA_basis_functions; aesop;
      -- Since each term in the sum is in the span of $DULA_basis_functions$, the entire sum is in the span.
      have h_sum_in_span : ∀ p ∈ primes_mod6 N, (fun x => (chi6 p) * (Real.log p / Real.sqrt p) * ((∫ y in Set.Icc 0 L, Real.cos (Real.log p * y) * f y) * Real.cos (Real.log p * x) + (∫ y in Set.Icc 0 L, Real.sin (Real.log p * y) * f y) * Real.sin (Real.log p * x))) ∈ Submodule.span ℝ (DULA_basis_functions N) := by
        intro p hp
        have h_term : (fun x => (∫ y in Set.Icc 0 L, Real.cos (Real.log p * y) * f y) * Real.cos (Real.log p * x) + (∫ y in Set.Icc 0 L, Real.sin (Real.log p * y) * f y) * Real.sin (Real.log p * x)) ∈ Submodule.span ℝ (DULA_basis_functions N) := by
          exact Submodule.add_mem _ ( Submodule.smul_mem _ _ ( Submodule.subset_span ( h_term_in_span p hp |>.1 ) ) ) ( Submodule.smul_mem _ _ ( Submodule.subset_span ( h_term_in_span p hp |>.2 ) ) );
        convert Submodule.smul_mem _ _ h_term using 1;
      convert Submodule.sum_mem _ h_sum_in_span using 1 ; ext ; aesop;

/-
The space L²([0,L]) is infinite dimensional for L > 0.
-/
lemma L2_Icc_infinite_dimensional (L : ℝ) (hL : 0 < L) :
    ¬ FiniteDimensional ℝ (MeasureTheory.Lp ℝ 2 (MeasureTheory.Measure.restrict volume (Set.Icc 0 L))) := by
  -- Define the function $f_n(x) = x^n$ for $n \geq 0$.
  set f : ℕ → ℝ → ℝ := fun n x => x^n;
  -- Show that $\{f_n\}$ is linearly independent in $L^2([0, L])$.
  have h_lin_indep : ∀ (s : Finset ℕ) (c : ℕ → ℝ), (∑ i ∈ s, c i • f i =ᵐ[MeasureTheory.Measure.restrict MeasureTheory.volume (Set.Icc 0 L)] 0) → (∀ i ∈ s, c i = 0) := by
    intros s c hc
    have h_poly_zero : ∀ᵐ x ∂MeasureTheory.Measure.restrict MeasureTheory.volume (Set.Icc 0 L), (∑ i ∈ s, c i * x^i) = 0 := by
      exact hc.mono fun x hx => by simpa using hx;
    -- Since $P(x)$ is a polynomial and $P(x) = 0$ almost everywhere on $[0, L]$, it follows that $P(x)$ is the zero polynomial.
    have h_poly_zero_poly : ∀ p : Polynomial ℝ, (∀ᵐ x ∂MeasureTheory.Measure.restrict MeasureTheory.volume (Set.Icc 0 L), p.eval x = 0) → p = 0 := by
      intro p hp
      by_contra h_nonzero_poly
      have h_inf_roots : Set.Infinite {x ∈ Set.Icc 0 L | p.eval x = 0} := by
        intro H; simp_all +decide [ MeasureTheory.ae_restrict_iff' ] ;
        rw [ Filter.eventually_inf_principal ] at hp;
        rw [ MeasureTheory.ae_iff ] at hp; simp_all +decide [ Set.Finite.measure_zero ] ;
        exact absurd hp ( by erw [ show { a : ℝ | 0 ≤ a ∧ a ≤ L ∧ ¬Polynomial.eval a p = 0 } = Set.Icc 0 L \ { x : ℝ | ( 0 ≤ x ∧ x ≤ L ) ∧ Polynomial.eval x p = 0 } by ext; aesop ] ; erw [ MeasureTheory.measure_diff_null ] <;> norm_num [ hL, H.measure_zero ] );
      exact h_inf_roots ( Set.Finite.subset ( p.roots.toFinset.finite_toSet ) fun x hx => by aesop );
    specialize h_poly_zero_poly ( ∑ i ∈ s, Polynomial.C ( c i ) * Polynomial.X ^ i ) ; simp_all +decide [ Polynomial.eval_finset_sum ] ;
    intro i hi; replace h_poly_zero_poly := congr_arg ( fun p => p.coeff i ) h_poly_zero_poly; aesop;
  contrapose! h_lin_indep with h_contra;
  -- Consider the map from the space of polynomials to $L^2([0, L])$ given by $p \mapsto p|_{[0, L]}$.
  set T : (Polynomial ℝ) →ₗ[ℝ] MeasureTheory.Lp ℝ 2 (MeasureTheory.Measure.restrict MeasureTheory.volume (Set.Icc 0 L)) :=
    { toFun := fun p => MeasureTheory.MemLp.toLp (fun x => p.eval x) (by
        refine' MeasureTheory.MemLp.mono' _ _ _;
        refine' fun x => ( SupSet.sSup ( Set.image ( fun x => |p.eval x| ) ( Set.Icc 0 L ) ) );
        · exact MeasureTheory.memLp_const _;
        · exact p.continuous.aestronglyMeasurable;
        · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Icc ] with x hx using le_csSup ( IsCompact.bddAbove ( isCompact_Icc.image ( p.continuous.abs ) ) ) ( Set.mem_image_of_mem _ hx )),
      map_add' := by
        aesop
        skip,
      map_smul' := by
        aesop
        skip };
  -- Since $T$ is a linear map from an infinite-dimensional space to a finite-dimensional space, it must have a non-trivial kernel.
  have h_kernel : ∃ p : Polynomial ℝ, p ≠ 0 ∧ T p = 0 := by
    have h_kernel : ¬ Function.Injective T := by
      intro h_inj
      have h_inf_dim : ¬FiniteDimensional ℝ (Polynomial ℝ) := by
        exact?
      exact h_inf_dim (by
      exact FiniteDimensional.of_injective T h_inj);
    simp_all +decide [ Function.Injective ];
    obtain ⟨ p, q, hpq, hpq' ⟩ := h_kernel; use p - q; simp_all +decide [ sub_eq_zero ] ;
  obtain ⟨ p, hp_ne_zero, hp_eq_zero ⟩ := h_kernel; use p.support, fun i => p.coeff i; simp_all +decide [ Polynomial.eval_eq_sum, Polynomial.sum_def ] ;
  -- Since $T(p) = 0$, we have that $p$ is zero almost everywhere on $[0, L]$.
  have h_ae_zero : ∀ᵐ x ∂MeasureTheory.Measure.restrict MeasureTheory.volume (Set.Icc 0 L), p.eval x = 0 := by
    rw [ Subtype.ext_iff ] at hp_eq_zero;
    erw [ MeasureTheory.AEEqFun.mk_eq_mk ] at hp_eq_zero ; aesop;
  simp_all +decide [ Filter.EventuallyEq, Filter.eventually_inf_principal ];
  exact ⟨ h_ae_zero.mono fun x hx hx' hx'' => by simpa [ Polynomial.eval_eq_sum, Polynomial.sum_def ] using hx hx' hx'', p.natDegree, by aesop ⟩

/-
The spectrum of H_DULA_compact is nonempty (contains at least 0).
-/
theorem spectrum_DULA_compact_nonempty (L : ℝ) (hL : 0 < L) (N : ℕ) :
    (spectrum_DULA_compact L N).Nonempty := by
  -- Let's choose any non-zero function $\psi$ in the kernel of $T$.
  obtain ⟨ψ, hψ⟩ : ∃ ψ : ℝ → ℝ, (MeasureTheory.MemLp ψ 2 (MeasureTheory.Measure.restrict volume (Set.Icc 0 L))) ∧ ¬(ψ =ᵐ[MeasureTheory.Measure.restrict volume (Set.Icc 0 L)] 0) ∧ ∀ x ∈ Set.Icc 0 L, H_DULA_compact L N ψ x = 0 := by
    -- By the properties of the linear map $T$, there exists a non-zero function $\psi$ in $L^2$ such that $T(\psi) = 0$.
    obtain ⟨ψ, hψ⟩ : ∃ ψ : MeasureTheory.Lp ℝ 2 (MeasureTheory.Measure.restrict volume (Set.Icc 0 L)), ψ ≠ 0 ∧ ∀ x ∈ Set.Icc 0 L, H_DULA_compact L N (fun x => ψ x) x = 0 := by
      -- Since $L^2([0, L])$ is infinite-dimensional and the range of $H_{\text{DULA}}^{\text{compact}}$ is finite-dimensional, there must exist a non-zero element in the kernel of $H_{\text{DULA}}^{\text{compact}}$.
      have h_kernel_nontrivial : ¬ Function.Injective (fun ψ : MeasureTheory.Lp ℝ 2 (MeasureTheory.Measure.restrict volume (Set.Icc 0 L)) => fun x => H_DULA_compact L N (fun x => ψ x) x) := by
        by_contra h_inj;
        -- Since $H_{\text{DULA}}^{\text{compact}}$ is injective, the range of $H_{\text{DULA}}^{\text{compact}}$ must be infinite-dimensional.
        have h_range_infinite_dimensional : ¬ FiniteDimensional ℝ (↥(Submodule.span ℝ (Set.range (fun ψ : MeasureTheory.Lp ℝ 2 (MeasureTheory.Measure.restrict volume (Set.Icc 0 L)) => fun x => H_DULA_compact L N (fun x => ψ x) x)))) := by
          have h_range_infinite_dimensional : ¬ FiniteDimensional ℝ (MeasureTheory.Lp ℝ 2 (MeasureTheory.Measure.restrict volume (Set.Icc 0 L))) := by
            exact?;
          intro h;
          refine' h_range_infinite_dimensional _;
          refine' h.of_injective _ _;
          refine' { .. };
          use fun ψ => ⟨ _, Submodule.subset_span ⟨ ψ, rfl ⟩ ⟩;
          all_goals norm_num [ Function.Injective ] at *;
          · intro a ha b hb; ext x; simp +decide [ H_DULA_compact ] ; ring;
            rw [ ← MeasureTheory.integral_add ];
            · rw [ MeasureTheory.integral_congr_ae ];
              filter_upwards [ a.coeFn_add b ] with y hy using by simp +decide [ hy, mul_add ] ;
            · refine' MeasureTheory.Integrable.mono' _ _ _;
              use fun y => ( ∑ p ∈ primes_mod6 N, |chi6 p| * ( Real.log p / Real.sqrt p ) ) * |a y|;
              · refine' MeasureTheory.Integrable.const_mul _ _;
                refine' MeasureTheory.Integrable.abs _;
                refine' MeasureTheory.MemLp.integrable one_le_two _;
                exact?;
              · refine' MeasureTheory.AEStronglyMeasurable.mul _ _;
                · refine' Continuous.aestronglyMeasurable _;
                  exact continuous_finset_sum _ fun _ _ => Continuous.mul ( Continuous.mul ( continuous_const ) ( continuous_const ) ) ( Real.continuous_cos.comp ( by continuity ) );
                · exact a.aestronglyMeasurable;
              · refine' Filter.Eventually.of_forall fun y => _;
                rw [ norm_mul ];
                gcongr;
                · refine' le_trans ( norm_sum_le _ _ ) _;
                  norm_num [ abs_mul, abs_div, abs_of_nonneg, Real.sqrt_nonneg, Real.log_nonneg ];
                  exact Finset.sum_le_sum fun i hi => mul_le_of_le_one_right ( mul_nonneg ( abs_nonneg _ ) ( div_nonneg ( abs_nonneg _ ) ( Real.sqrt_nonneg _ ) ) ) ( Real.abs_cos_le_one _ ) |> le_trans <| by rw [ abs_of_nonneg ( Real.log_nonneg <| Nat.one_le_cast.mpr <| Nat.Prime.pos <| by { unfold primes_mod6 at hi; aesop } ) ] ;
                · norm_num [ Norm.norm ];
            · refine' MeasureTheory.Integrable.mono' _ _ _;
              use fun y => ( ∑ p ∈ primes_mod6 N, |chi6 p| * ( Real.log p / Real.sqrt p ) ) * |b y|;
              · refine' MeasureTheory.Integrable.const_mul _ _;
                refine' MeasureTheory.Integrable.abs _;
                refine' MeasureTheory.MemLp.integrable one_le_two _;
                exact?;
              · refine' MeasureTheory.AEStronglyMeasurable.mul _ _;
                · refine' Continuous.aestronglyMeasurable _;
                  exact continuous_iff_continuousAt.mpr fun y => by exact tendsto_finset_sum _ fun p hp => ContinuousAt.mul ( ContinuousAt.mul ( continuousAt_const ) ( continuousAt_const ) ) ( Real.continuous_cos.continuousAt.comp <| ContinuousAt.mul continuousAt_const <| continuousAt_const.sub continuousAt_id ) ;
                · exact b.aestronglyMeasurable;
              · refine' Filter.Eventually.of_forall fun y => _;
                rw [ norm_mul ];
                gcongr;
                · refine' le_trans ( norm_sum_le _ _ ) _;
                  norm_num [ abs_mul, abs_div, abs_of_nonneg, Real.sqrt_nonneg, Real.log_nonneg ];
                  exact Finset.sum_le_sum fun i hi => mul_le_of_le_one_right ( mul_nonneg ( abs_nonneg _ ) ( div_nonneg ( abs_nonneg _ ) ( Real.sqrt_nonneg _ ) ) ) ( Real.abs_cos_le_one _ ) |> le_trans <| by rw [ abs_of_nonneg ( Real.log_nonneg <| Nat.one_le_cast.mpr <| Nat.Prime.pos <| by { exact Finset.mem_filter.mp hi |>.2.1 } ) ] ;
                · norm_num [ Norm.norm ];
          · intro m a ha; ext x; simp +decide [ H_DULA_compact, mul_assoc, mul_left_comm, Finset.mul_sum _ _ _ ] ;
            rw [ ← MeasureTheory.integral_const_mul ];
            rw [ MeasureTheory.integral_congr_ae ];
            filter_upwards [ MeasureTheory.Lp.coeFn_smul m ⟨ a, ha ⟩ ] with y hy using by simp +decide [ hy, mul_assoc, mul_left_comm ] ;
          · intro a ha b hb hab; specialize @h_inj ⟨ a, ha ⟩ ⟨ b, hb ⟩ ; aesop;
        -- However, we have that the range of $H_{\text{DULA}}^{\text{compact}}$ is contained in the span of the finite set $DULA_{\text{basis\_functions}}$.
        have h_range_subset_span : Set.range (fun ψ : MeasureTheory.Lp ℝ 2 (MeasureTheory.Measure.restrict volume (Set.Icc 0 L)) => fun x => H_DULA_compact L N (fun x => ψ x) x) ⊆ Submodule.span ℝ (DULA_basis_functions N : Set (ℝ → ℝ)) := by
          rintro _ ⟨ ψ, rfl ⟩ ; exact H_DULA_compact_range_subset_span L N _ <| by
            exact MeasureTheory.MemLp.integrable one_le_two ( MeasureTheory.Lp.memLp ψ );
        refine' h_range_infinite_dimensional _;
        have h_finite_dimensional : FiniteDimensional ℝ (↥(Submodule.span ℝ (DULA_basis_functions N : Set (ℝ → ℝ)))) := by
          exact FiniteDimensional.span_of_finite _ ( Finset.finite_toSet _ );
        exact h_finite_dimensional.of_injective ( Submodule.inclusion ( show Submodule.span ℝ ( Set.range fun ψ : ↥ ( MeasureTheory.Lp ℝ 2 ( MeasureTheory.MeasureSpace.volume.restrict ( Set.Icc 0 L ) ) ) => fun x => H_DULA_compact L N ( fun x => ( ψ : ℝ → ℝ ) x ) x ) ≤ Submodule.span ℝ ( DULA_basis_functions N : Set ( ℝ → ℝ ) ) from Submodule.span_le.mpr h_range_subset_span ) ) ( Submodule.inclusion_injective _ );
      simp_all +decide [ Function.Injective ];
      obtain ⟨ x, hx, y, hy, hxy, hne ⟩ := h_kernel_nontrivial; use x - y; simp_all +decide [ funext_iff, sub_eq_zero ] ;
      refine' ⟨ _, _ ⟩;
      · exact?;
      · intro x_1 hx_1 hx_1'; simp_all +decide [ H_DULA_compact ] ;
        rw [ MeasureTheory.integral_congr_ae ];
        any_goals exact fun z => DULA_kernel N x_1 z * ( x z - y z );
        · simp_all +decide [ mul_sub ];
          rw [ MeasureTheory.integral_sub, hxy, sub_self ];
          · refine' MeasureTheory.Integrable.mono' _ _ _;
            refine' fun a => ( ∑ p ∈ primes_mod6 N, |chi6 p| * ( |Real.log p| / Real.sqrt p ) ) * |x a|;
            · refine' MeasureTheory.Integrable.const_mul _ _;
              refine' MeasureTheory.Integrable.abs _;
              refine' MeasureTheory.MemLp.integrable one_le_two _;
              exact?;
            · refine' MeasureTheory.AEStronglyMeasurable.mul _ _;
              · exact Continuous.aestronglyMeasurable ( by exact continuous_finset_sum _ fun _ _ => Continuous.mul ( Continuous.mul ( continuous_const ) ( continuous_const ) ) ( Real.continuous_cos.comp ( by continuity ) ) );
              · exact x.aestronglyMeasurable;
            · refine' Filter.Eventually.of_forall fun a => _;
              rw [ norm_mul ];
              gcongr;
              · refine' le_trans ( norm_sum_le _ _ ) _;
                norm_num [ abs_div, abs_mul, abs_of_nonneg, Real.sqrt_nonneg ];
                exact Finset.sum_le_sum fun _ _ => mul_le_of_le_one_right ( by positivity ) ( Real.abs_cos_le_one _ );
              · norm_num [ Norm.norm ];
          · refine' MeasureTheory.Integrable.mono' _ _ _;
            refine' fun a => ( ∑ p ∈ primes_mod6 N, |chi6 p| * ( Real.log p / Real.sqrt p ) ) * |y a|;
            · refine' MeasureTheory.Integrable.const_mul _ _;
              refine' MeasureTheory.Integrable.abs _;
              refine' MeasureTheory.MemLp.integrable one_le_two _;
              exact?;
            · refine' MeasureTheory.AEStronglyMeasurable.mul _ _;
              · exact Continuous.aestronglyMeasurable ( by exact continuous_finset_sum _ fun _ _ => Continuous.mul ( continuous_const ) ( Real.continuous_cos.comp ( by continuity ) ) );
              · exact y.aestronglyMeasurable;
            · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Icc ] with a ha;
              rw [ norm_mul ];
              gcongr;
              · refine' le_trans ( norm_sum_le _ _ ) _;
                norm_num [ abs_mul, abs_div, abs_of_nonneg, Real.sqrt_nonneg, Real.log_nonneg ];
                exact Finset.sum_le_sum fun p hp => mul_le_of_le_one_right ( by positivity ) ( Real.abs_cos_le_one _ ) |> le_trans <| by rw [ abs_of_nonneg ( Real.log_nonneg <| Nat.one_le_cast.mpr <| Nat.Prime.pos <| by unfold primes_mod6 at hp; aesop ) ] ;
              · norm_num [ Norm.norm ];
        · filter_upwards [ x.coeFn_sub y ] with z hz using by aesop;
    -- Since ψ is non-zero in the Lp space, its representative is not almost everywhere zero.
    have h_nonzero : ¬(ψ =ᵐ[MeasureTheory.Measure.restrict MeasureTheory.volume (Set.Icc 0 L)] 0) := by
      intro h_zero_ae
      have h_zero_in_Lp : ψ = 0 := by
        exact?
      exact hψ.left h_zero_in_Lp;
    exact ⟨ _, MeasureTheory.Lp.memLp _, h_nonzero, hψ.2 ⟩;
  use 0; use ψ; aesop;

/-
The span of the DULA basis functions is finite dimensional.
-/
theorem DULA_range_finite_dimensional (N : ℕ) :
    FiniteDimensional ℝ (Submodule.span ℝ (DULA_basis_functions N : Set (ℝ → ℝ))) := by
  exact FiniteDimensional.span_of_finite ℝ (Finset.finite_toSet (DULA_basis_functions N))

/-
The subspace spanned by the DULA basis functions.
-/
def DULA_span (N : ℕ) : Submodule ℝ (ℝ → ℝ) :=
  Submodule.span ℝ (DULA_basis_functions N)

/-
H_DULA_compact maps the span of basis functions to itself.
-/
theorem H_DULA_maps_span_to_span (L : ℝ) (N : ℕ) (f : DULA_span N) :
    H_DULA_compact L N f.1 ∈ DULA_span N := by
  apply H_DULA_compact_range_subset_span
  -- We need to show f.1 is integrable on [0,L]
  -- Elements of DULA_span are finite linear combinations of continuous functions (cos, sin)
  -- Hence they are continuous on [0,L], hence integrable on [0,L]
  refine' ContinuousOn.integrableOn_Icc _;
  refine' Continuous.continuousOn _;
  have h_cont : ∀ p ∈ primes_mod6 N, Continuous (fun x => Real.cos (Real.log p * x)) ∧ Continuous (fun x => Real.sin (Real.log p * x)) := by
    exact fun p hp => ⟨ Real.continuous_cos.comp <| continuous_const.mul continuous_id', Real.continuous_sin.comp <| continuous_const.mul continuous_id' ⟩;
  refine' Submodule.span_induction _ _ _ _ f.2;
  · unfold DULA_basis_functions; aesop;
  · fun_prop;
  · exact fun x y hx hy hx' hy' => hx'.add hy';
  · exact fun a x hx hx' => continuous_const.mul hx'

/-
The restriction of H_DULA_compact to the finite-dimensional subspace DULA_span.
-/
noncomputable def H_DULA_restricted (L : ℝ) (N : ℕ) : DULA_span N →ₗ[ℝ] DULA_span N :=
  { toFun := fun f => ⟨H_DULA_compact L N f.1, H_DULA_maps_span_to_span L N f⟩,
    map_add' := by
      intro x y; ext; simp +decide [ H_DULA_compact ] ; ring;
      rw [ MeasureTheory.integral_add ];
      · refine' ContinuousOn.integrableOn_Icc _;
        refine' ContinuousOn.mul _ _;
        · exact Continuous.continuousOn ( by exact continuous_finset_sum _ fun _ _ => Continuous.mul ( Continuous.mul ( continuous_const ) ( continuous_const.div_const _ ) ) ( Real.continuous_cos.comp ( by continuity ) ) );
        · -- Since $x$ is in the span of the DULA basis functions, it is a finite linear combination of continuous functions.
          have h_cont : ContinuousOn (fun x_1 => x.val x_1) (Set.Icc 0 L) := by
            have h_basis_cont : ∀ p ∈ primes_mod6 N, ContinuousOn (fun x_1 => Real.cos (Real.log p * x_1)) (Set.Icc 0 L) ∧ ContinuousOn (fun x_1 => Real.sin (Real.log p * x_1)) (Set.Icc 0 L) := by
              exact fun p hp => ⟨ Continuous.continuousOn <| Real.continuous_cos.comp <| by continuity, Continuous.continuousOn <| Real.continuous_sin.comp <| by continuity ⟩
            have h_cont : ∀ f ∈ DULA_basis_functions N, ContinuousOn (fun x_1 => f x_1) (Set.Icc 0 L) := by
              unfold DULA_basis_functions; aesop;
            generalize_proofs at *; (
            have h_cont : ∀ f ∈ DULA_span N, ContinuousOn (fun x_1 => f x_1) (Set.Icc 0 L) := by
              intro f hf
              induction' hf using Submodule.span_induction with f hf ih
              all_goals generalize_proofs at *;
              · exact h_cont f hf;
              · exact continuousOn_const;
              · exact ContinuousOn.add ‹_› ‹_›;
              · exact ContinuousOn.mul continuousOn_const ‹_›
                skip
            generalize_proofs at *; (exact h_cont _ x.2))
          generalize_proofs at *; (
          exact h_cont);
      · refine' Continuous.integrableOn_Icc _;
        refine' Continuous.mul _ _;
        · exact continuous_finset_sum _ fun _ _ => Continuous.mul ( Continuous.mul ( continuous_const ) ( continuous_const ) ) ( Real.continuous_cos.comp ( by continuity ) );
        · -- Since $y$ is in the span of the DULA basis functions, it is a finite linear combination of continuous functions, hence continuous.
          have h_cont : Continuous (y : ℝ → ℝ) := by
            have h_basis_cont : ∀ p ∈ primes_mod6 N, Continuous (fun x => Real.cos (Real.log p * x)) ∧ Continuous (fun x => Real.sin (Real.log p * x)) := by
              exact fun p hp => ⟨ Real.continuous_cos.comp <| continuous_const.mul continuous_id', Real.continuous_sin.comp <| continuous_const.mul continuous_id' ⟩
              skip
            have h_cont : ∀ f ∈ DULA_span N, Continuous f := by
              intro f hf; exact (by
              refine' Submodule.span_induction _ _ _ _ hf <;> norm_num +zetaDelta at *;
              · unfold DULA_basis_functions; aesop;
              · exact continuous_zero;
              · exact fun x y hx hy hx' hy' => hx'.add hy';
              · exact fun a x hx hx' => continuous_const.mul hx');
            generalize_proofs at *; (
            exact h_cont _ y.2)
          generalize_proofs at *; (
          exact h_cont),
    map_smul' := by
      intro m x; ext; simp [H_DULA_compact];
      simp +decide only [mul_left_comm, ← integral_const_mul] }

/-
Functions in the DULA span are determined by their values on [0,L].
-/
lemma DULA_span_eq_of_eq_on_Icc (L : ℝ) (hL : 0 < L) (N : ℕ) (f g : DULA_span N)
    (h_eq : ∀ x ∈ Set.Icc 0 L, f.1 x = g.1 x) : f = g := by
  -- Elements of DULA_span are sums of cos(k*x) and sin(k*x).
  -- These are analytic functions.
  -- If two analytic functions agree on an interval [0,L] with L > 0, they agree everywhere.
  -- Since $f$ and $g$ are both linear combinations of $\cos(kx)$ and $\sin(kx)$, they are real analytic functions.
  have h_analytic : ∀ (f : ℝ → ℝ), f ∈ DULA_span N → AnalyticOn ℝ f Set.univ := by
    intro f hf
    have h_cos_sin : ∀ p ∈ primes_mod6 N, AnalyticOn ℝ (fun x => Real.cos (Real.log p * x)) Set.univ ∧ AnalyticOn ℝ (fun x => Real.sin (Real.log p * x)) Set.univ := by
      intros p hp
      have h_cos_sin_analytic : AnalyticOn ℝ (fun x => Real.cos x) Set.univ ∧ AnalyticOn ℝ (fun x => Real.sin x) Set.univ := by
        apply And.intro;
        · exact?;
        · exact?;
      exact ⟨ h_cos_sin_analytic.1.comp ( analyticOn_const.mul analyticOn_id ) fun x hx => by simpa, h_cos_sin_analytic.2.comp ( analyticOn_const.mul analyticOn_id ) fun x hx => by simpa ⟩;
    refine' Submodule.span_induction _ _ _ _ hf;
    · unfold DULA_basis_functions; aesop;
    · exact analyticOn_const;
    · exact fun x y hx hy hx' hy' => hx'.add hy';
    · exact fun a x hx hx' => by exact AnalyticOn.mul ( analyticOn_const ) hx';
  -- Since $f$ and $g$ are real analytic and agree on the interval $[0, L]$, they must be equal everywhere.
  have h_eq_analytic : ∀ (f g : ℝ → ℝ), AnalyticOn ℝ f Set.univ → AnalyticOn ℝ g Set.univ → (∀ x ∈ Set.Icc 0 L, f x = g x) → f = g := by
    intros f g hf hg h_eq; ext x; exact (by
    simp +zetaDelta at *;
    apply hf.eqOn_of_preconnected_of_eventuallyEq hg;
    exact isPreconnected_univ;
    exacts [ Set.mem_univ ( L / 2 ), Filter.eventually_of_mem ( Icc_mem_nhds ( by linarith ) ( by linarith ) ) fun x hx => h_eq x hx.1 hx.2, Set.mem_univ x ]);
  exact Subtype.ext <| h_eq_analytic _ _ ( h_analytic _ f.2 ) ( h_analytic _ g.2 ) h_eq

/-
H_DULA_compact depends only on the values of the function on the interval [0,L].
-/
lemma H_DULA_compact_congr (L : ℝ) (N : ℕ) (f g : ℝ → ℝ)
    (h : ∀ x ∈ Set.Icc 0 L, f x = g x) :
    H_DULA_compact L N f = H_DULA_compact L N g := by
      unfold H_DULA_compact;
      ext x; exact MeasureTheory.setIntegral_congr_fun measurableSet_Icc fun y hy => by rw [ h y hy ] ;

/-
Every non-zero eigenvalue of H_DULA_compact corresponds to an eigenvector in the finite-dimensional subspace DULA_span.
-/
theorem nonzero_eigenvalue_is_restricted_eigenvalue (L : ℝ) (hL : 0 < L) (N : ℕ) (μ : ℝ) (hμ : μ ≠ 0)
    (h_mem : μ ∈ spectrum_DULA_compact L N) :
    ∃ g : DULA_span N, g ≠ 0 ∧ H_DULA_restricted L N g = μ • g := by
  obtain ⟨ ψ, hψ_mem, hψ_eq ⟩ := h_mem;
  -- Define g = (1/μ) * H_DULA_compact(ψ).
  set g : ℝ → ℝ := fun x => (1 / μ) * H_DULA_compact L N ψ x;
  -- Since Range(H) ⊆ DULA_span, g ∈ DULA_span.
  have hg_span : g ∈ DULA_span N := by
    have hg_span : H_DULA_compact L N ψ ∈ Submodule.span ℝ (DULA_basis_functions N : Set (ℝ → ℝ)) := by
      apply H_DULA_compact_range_subset_span L N ψ (hψ_mem.integrable one_le_two);
    convert Submodule.smul_mem _ ( 1 / μ ) hg_span using 1;
  -- Since H(g) and μ g are both in DULA_span (analytic), and agree on [0,L], they agree everywhere (DULA_span_eq_of_eq_on_Icc).
  have hg_eq_all : H_DULA_compact L N g = μ • g := by
    rw [ H_DULA_compact_congr L N g ψ ];
    · aesop;
    · aesop;
  refine' ⟨ ⟨ g, hg_span ⟩, _, _ ⟩ <;> simp_all +decide [ funext_iff, Subtype.ext_iff ];
  · contrapose! hψ_eq;
    rw [ Filter.EventuallyEq, Filter.eventually_inf_principal ] ; aesop;
  · exact hg_eq_all

/-
The spectrum of H_DULA_compact is a finite set.
-/
theorem spectrum_DULA_compact_finite (L : ℝ) (hL : 0 < L) (N : ℕ) :
    (spectrum_DULA_compact L N).Finite := by
  -- Let E be the set of eigenvalues of H_DULA_restricted.
  set E := {μ : ℝ | ∃ g : DULA_span N, g ≠ 0 ∧ H_DULA_restricted L N g = μ • g};
  -- Since DULA_span is finite-dimensional, E is finite.
  have hE_finite : E.Finite := by
    by_contra hE_infinite
    have h_trace : ∀ μ : ℝ, μ ∈ E → μ ∈ spectrum ℝ (H_DULA_restricted L N) := by
      intro μ hμ
      obtain ⟨g, hg_ne_zero, hg_eigenvalue⟩ := hμ
      have h_eigenvalue : H_DULA_restricted L N g = μ • g := by
        exact hg_eigenvalue
      have h_spectrum : μ ∈ spectrum ℝ (H_DULA_restricted L N) := by
        intro h_unit; have := h_unit.exists_left_inv; obtain ⟨ f, hf ⟩ := this; replace hf := congr_arg ( fun f => f g ) hf; simp_all +decide [ sub_eq_iff_eq_add ] ;
      exact h_spectrum
      skip
    have h_inf_spectrum : Set.Infinite (spectrum ℝ (H_DULA_restricted L N)) := by
      exact Set.Infinite.mono h_trace hE_infinite;
    have h_finite_spectrum : Set.Finite (spectrum ℝ (H_DULA_restricted L N)) := by
      have h_finite_spectrum : FiniteDimensional ℝ (DULA_span N) := by
        convert DULA_range_finite_dimensional N using 1
      generalize_proofs at *; (
      exact?)
    exact h_inf_spectrum h_finite_spectrum;
  -- By nonzero_eigenvalue_is_restricted_eigenvalue, S_nonzero ⊆ E.
  have hS_nonzero_subset_E : {μ : ℝ | μ ∈ spectrum_DULA_compact L N ∧ μ ≠ 0} ⊆ E := by
    exact fun μ hμ => nonzero_eigenvalue_is_restricted_eigenvalue L hL N μ hμ.2 hμ.1;
  exact Set.Finite.subset ( hE_finite.union ( Set.finite_singleton 0 ) ) fun x hx => if hx0 : x = 0 then Or.inr hx0 else Or.inl ( hS_nonzero_subset_E ⟨ hx, hx0 ⟩ )

/-
Functions in the DULA span are in L²([0,L]).
-/
theorem DULA_span_subset_Lp (L : ℝ) (hL : 0 < L) (N : ℕ) (g : DULA_span N) :
    MeasureTheory.MemLp g.1 2 (MeasureTheory.Measure.restrict volume (Set.Icc 0 L)) := by
  -- Elements of DULA_span are finite linear combinations of continuous functions.
  -- Hence they are continuous on the compact interval [0,L].
  -- Continuous functions on a compact set are bounded and measurable, hence in Lp for any p.
  -- Since g is a finite linear combination of continuous functions (cos and sin), it's continuous.
  have h_cont : Continuous (g : ℝ → ℝ) := by
    have h_cont : ∀ p ∈ primes_mod6 N, Continuous (fun x => Real.cos (Real.log p * x)) ∧ Continuous (fun x => Real.sin (Real.log p * x)) := by
      exact fun p hp => ⟨ Real.continuous_cos.comp <| continuous_const.mul continuous_id', Real.continuous_sin.comp <| continuous_const.mul continuous_id' ⟩;
    refine' Submodule.span_induction _ _ _ _ g.2;
    · unfold DULA_basis_functions; aesop;
    · exact continuous_zero;
    · exact fun x y hx hy hx' hy' => hx'.add hy';
    · exact fun a x hx hx' => continuous_const.mul hx';
  refine' MeasureTheory.MemLp.mono' _ _ _;
  exact fun x => SupSet.sSup ( Set.image ( fun x => |( g : ℝ → ℝ ) x| ) ( Set.Icc 0 L ) );
  · exact MeasureTheory.memLp_const _;
  · exact h_cont.aestronglyMeasurable;
  · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Icc ] with x hx using le_csSup ( IsCompact.bddAbove ( isCompact_Icc.image ( continuous_abs.comp h_cont ) ) ) ( Set.mem_image_of_mem _ hx )

/-
The operator H_DULA_compact is bounded on L²([0,L]).
-/
theorem H_DULA_compact_bounded (L : ℝ) (hL : 0 < L) (N : ℕ) :
    ∃ C : ℝ, C ≥ 0 ∧ ∀ f : ℝ → ℝ,
      MeasureTheory.MemLp f 2 (MeasureTheory.Measure.restrict volume (Set.Icc 0 L)) →
      MeasureTheory.MemLp (H_DULA_compact L N f) 2 (MeasureTheory.Measure.restrict volume (Set.Icc 0 L)) ∧
      MeasureTheory.eLpNorm (H_DULA_compact L N f) 2 (MeasureTheory.Measure.restrict volume (Set.Icc 0 L)) ≤
      ENNReal.ofReal C * MeasureTheory.eLpNorm f 2 (MeasureTheory.Measure.restrict volume (Set.Icc 0 L)) := by
  -- The kernel is bounded (DULA_kernel_bounded).
  -- Let M be the bound.
  -- |(H f)(x)| <= M * sqrt(L) * ||f||_2.
  -- ||H f||_2 <= M * L * ||f||_2.
  -- Let $M$ be the bound on the kernel $K$ (from DULA_kernel_bounded).
  obtain ⟨M, hM⟩ : ∃ M, ∀ x y, |DULA_kernel N x y| ≤ M := by
    exact?;
  refine' ⟨ M * L, mul_nonneg ( le_trans ( abs_nonneg _ ) ( hM 0 0 ) ) hL.le, fun f hf => ⟨ _, _ ⟩ ⟩;
  · -- Since the DULA span is finite-dimensional, any function in it is in L²([0,L]).
    have h_finite_dim : ∀ g : DULA_span N, MeasureTheory.MemLp g.1 2 (MeasureTheory.Measure.restrict volume (Set.Icc 0 L)) := by
      exact?;
    convert h_finite_dim ⟨ H_DULA_compact L N f, H_DULA_compact_range_subset_span L N f ( hf.integrable one_le_two ) ⟩ using 1;
  · -- By Hölder's inequality, we have |H f(x)| ≤ M * ∫ |f(y)| dy.
    have h_holder : ∀ x ∈ Set.Icc 0 L, |H_DULA_compact L N f x| ≤ M * ∫ y in Set.Icc 0 L, |f y| := by
      intro x hx
      have h_integral_bound : |∫ y in Set.Icc 0 L, DULA_kernel N x y * f y| ≤ ∫ y in Set.Icc 0 L, M * |f y| := by
        refine' le_trans ( MeasureTheory.norm_integral_le_integral_norm ( _ : ℝ → ℝ ) ) ( MeasureTheory.integral_mono_of_nonneg _ _ _ );
        · exact Filter.Eventually.of_forall fun y => norm_nonneg _;
        · exact MeasureTheory.Integrable.const_mul ( hf.norm.integrable one_le_two ) _;
        · filter_upwards [ ] with y using by simpa [ abs_mul ] using mul_le_mul_of_nonneg_right ( hM x y ) ( abs_nonneg ( f y ) ) ;
      simpa only [ MeasureTheory.integral_const_mul ] using h_integral_bound;
    -- By the properties of the L2 norm, we can bound ‖H_DULA_compact L N f‖₂ by M * L * ‖f‖₂.
    have h_norm : MeasureTheory.eLpNorm (H_DULA_compact L N f) 2 (MeasureTheory.MeasureSpace.volume.restrict (Set.Icc 0 L)) ≤ ENNReal.ofReal (M * ∫ y in Set.Icc 0 L, |f y|) * ENNReal.ofReal (Real.sqrt L) := by
      rw [ MeasureTheory.eLpNorm_eq_lintegral_rpow_enorm ];
      · refine' le_trans ( ENNReal.rpow_le_rpow ( MeasureTheory.lintegral_mono_ae _ ) _ ) _;
        use fun x => ENNReal.ofReal ( M * ∫ y in Set.Icc 0 L, |f y| ) ^ 2;
        · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Icc ] with x hx;
          convert pow_le_pow_left₀ ( by positivity ) ( ENNReal.ofReal_le_ofReal ( h_holder x hx ) ) 2 using 1 ; norm_num [ ENNReal.ofReal ];
          norm_cast;
        · norm_num;
        · norm_num [ ENNReal.ofReal_rpow_of_nonneg, hL.le ];
          rw [ ENNReal.mul_rpow_of_nonneg ] <;> norm_num;
          rw [ ← ENNReal.rpow_natCast, ← ENNReal.rpow_mul ] ; norm_num [ Real.sqrt_eq_rpow, ENNReal.ofReal_rpow_of_nonneg, hL.le ];
      · norm_num;
      · norm_num;
    -- By the properties of the L2 norm, we can bound ‖f‖₂ by √L * ‖f‖₂.
    have h_norm_f : ∫ y in Set.Icc 0 L, |f y| ≤ Real.sqrt L * (MeasureTheory.eLpNorm f 2 (MeasureTheory.MeasureSpace.volume.restrict (Set.Icc 0 L))).toReal := by
      have h_cauchy_schwarz : ∀ {g h : ℝ → ℝ}, MeasureTheory.MemLp g 2 (MeasureTheory.MeasureSpace.volume.restrict (Set.Icc 0 L)) → MeasureTheory.MemLp h 2 (MeasureTheory.MeasureSpace.volume.restrict (Set.Icc 0 L)) → ∫ y in Set.Icc 0 L, |g y * h y| ≤ (∫ y in Set.Icc 0 L, |g y|^2)^(1/2 : ℝ) * (∫ y in Set.Icc 0 L, |h y|^2)^(1/2 : ℝ) := by
        intros g h hg hh;
        have := @MeasureTheory.integral_mul_norm_le_Lp_mul_Lq;
        convert @this ℝ _ ( MeasureTheory.Measure.restrict MeasureTheory.volume ( Set.Icc 0 L ) ) ℝ _ g h 2 2 _ _ _ using 1 <;> norm_num [ hg, hh ];
        exact?;
      convert @h_cauchy_schwarz f ( fun _ => 1 ) hf ( MeasureTheory.memLp_const _ ) using 1 <;> norm_num [ Real.sqrt_eq_rpow, MeasureTheory.eLpNorm_eq_lintegral_rpow_enorm ];
      rw [ max_eq_left hL.le, MeasureTheory.integral_eq_lintegral_of_nonneg_ae ];
      · norm_num [ mul_comm, ENNReal.toReal_rpow ];
        norm_num [ ← ENNReal.ofReal_coe_nnreal, Real.enorm_eq_ofReal_abs ];
        norm_num [ ← ENNReal.ofReal_pow, abs_mul ];
      · exact Filter.Eventually.of_forall fun x => sq_nonneg _;
      · exact MeasureTheory.AEStronglyMeasurable.pow ( hf.1 ) _;
    refine' le_trans h_norm _;
    rw [ ← ENNReal.ofReal_mul ( mul_nonneg ( show 0 ≤ M by exact le_trans ( abs_nonneg _ ) ( hM 0 0 ) ) ( show 0 ≤ ∫ y in Set.Icc 0 L, |f y| by exact MeasureTheory.integral_nonneg fun _ => abs_nonneg _ ) ) ];
    rw [ ENNReal.ofReal_le_iff_le_toReal ] <;> norm_num;
    · rw [ ENNReal.toReal_ofReal ( mul_nonneg ( show 0 ≤ M by exact le_trans ( abs_nonneg _ ) ( hM 0 0 ) ) hL.le ) ];
      convert mul_le_mul_of_nonneg_left h_norm_f ( show 0 ≤ M * Real.sqrt L by exact mul_nonneg ( le_trans ( abs_nonneg _ ) ( hM 0 0 ) ) ( Real.sqrt_nonneg _ ) ) using 1 ; ring ; ring;
      rw [ Real.sq_sqrt ] <;> linarith;
    · exact ENNReal.mul_ne_top ( ENNReal.ofReal_ne_top ) ( hf.eLpNorm_lt_top.ne )

/-
The operator H_DULA_compact is bounded on L²([0,L]).
-/
theorem H_DULA_compact_is_bounded (L : ℝ) (hL : 0 < L) (N : ℕ) :
    ∃ C : ℝ, C ≥ 0 ∧ ∀ f : ℝ → ℝ,
      MeasureTheory.MemLp f 2 (MeasureTheory.Measure.restrict volume (Set.Icc 0 L)) →
      MeasureTheory.MemLp (H_DULA_compact L N f) 2 (MeasureTheory.Measure.restrict volume (Set.Icc 0 L)) ∧
      MeasureTheory.eLpNorm (H_DULA_compact L N f) 2 (MeasureTheory.Measure.restrict volume (Set.Icc 0 L)) ≤
      ENNReal.ofReal C * MeasureTheory.eLpNorm f 2 (MeasureTheory.Measure.restrict volume (Set.Icc 0 L)) := by
  -- The kernel is bounded (DULA_kernel_bounded).
  -- Let M be the bound.
  -- |(H f)(x)| <= M * sqrt(L) * ||f||_2.
  -- ||H f||_2 <= M * L * ||f||_2.
  exact?
