/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: d161316f-19a9-48f9-85b0-0fce04471d92

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
The user requested a proof of the functional equation for the Grand Partition Function `Grand_Z_DULA`.
We defined `class_weight` and `Grand_Z_DULA` as requested.
We then proved the theorem `Grand_Partition_Functional_Equation_Ultimate'` which establishes the functional equation
by summing the individual functional equations for each term.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definition of class weight for an element g in a group M acting on itself.
-/
open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

variable (M : Type) [Group M] [Fintype M]
variable [MulAction M M]

noncomputable def class_weight (g : M) [Fintype ↑(MulAction.orbit M g)] : ℝ :=
  (Fintype.card ↑(MulAction.orbit M g) : ℝ) / (Fintype.card M : ℝ)

/-
Definition of Grand_Z_DULA.
-/
open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

variable (M : Type) [Group M] [Fintype M]
variable [MulAction M M]
variable (Lambda_DULA : M → ℂ → ℂ)
variable (ConjugacyClasses : Finset M)

noncomputable def Grand_Z_DULA (s : ℂ) : ℂ :=
  ∑ g ∈ ConjugacyClasses, (class_weight M g) * (Lambda_DULA g s)

/-
Functional equation for the Grand Partition Function.
-/
open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

theorem Grand_Partition_Functional_Equation_Ultimate
  (M : Type) [Group M] [Fintype M] [MulAction M M]
  (epsilon_g : M → ℝ)
  (Lambda_DULA : M → ℂ → ℂ)
  (ConjugacyClasses : Finset M)
  (Individual_Functional_Equation : ∀ (g : M) (s : ℂ), Lambda_DULA g s = epsilon_g g * Lambda_DULA g (1 - s))
  (s : ℂ) :
  Grand_Z_DULA M Lambda_DULA ConjugacyClasses s = 
  ∑ g ∈ ConjugacyClasses, (class_weight M g) * (epsilon_g g) * Lambda_DULA g (1 - s) := by
  unfold Grand_Z_DULA
  apply Finset.sum_congr rfl
  intro g _
  rw [Individual_Functional_Equation g s]
  push_cast
  ring

/-
Helper lemma: Functional equation holds for each term in the sum.
-/
theorem Grand_Partition_Functional_Equation_term
  (M : Type) [Group M] [Fintype M] [MulAction M M]
  (epsilon_g : M → ℝ)
  (Lambda_DULA : M → ℂ → ℂ)
  (Individual_Functional_Equation : ∀ (g : M) (s : ℂ), Lambda_DULA g s = epsilon_g g * Lambda_DULA g (1 - s))
  (g : M) (s : ℂ) :
  (class_weight M g : ℂ) * (Lambda_DULA g s) = (class_weight M g : ℂ) * (epsilon_g g : ℂ) * Lambda_DULA g (1 - s) := by
  rw [Individual_Functional_Equation g s]
  push_cast
  ring

/-
Final theorem: Functional equation for the Grand Partition Function (proved).
-/
theorem Grand_Partition_Functional_Equation_Ultimate'
  (M : Type) [Group M] [Fintype M] [MulAction M M]
  (epsilon_g : M → ℝ)
  (Lambda_DULA : M → ℂ → ℂ)
  (ConjugacyClasses : Finset M)
  (Individual_Functional_Equation : ∀ (g : M) (s : ℂ), Lambda_DULA g s = epsilon_g g * Lambda_DULA g (1 - s))
  (s : ℂ) :
  Grand_Z_DULA M Lambda_DULA ConjugacyClasses s = 
  ∑ g ∈ ConjugacyClasses, (class_weight M g) * (epsilon_g g) * Lambda_DULA g (1 - s) := by
  unfold Grand_Z_DULA
  apply Finset.sum_congr rfl
  intro g _
  apply Grand_Partition_Functional_Equation_term M epsilon_g Lambda_DULA Individual_Functional_Equation g s