/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: e0565165-6913-4e5d-a8dc-9e54ad8a34a3

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
D₄ (24-Cell) Finite-Rank Perturbation Model with explicit Hurwitz coordinates and full spectral proofs.
Includes definitions of vertices, charges, and the perturbation matrix.
Formal proofs are provided for:
- Energy conservation (Trace = 24)
- Twin-Prime Null Zone (Structure factor at k=0 is 0)
- Resonance peak (Non-zero eigenvalue λ = 24)
- Twin-prime bound state (Kernel / eigenvalue λ = 0)
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

abbrev R4 := ℝ × ℝ × ℝ × ℝ

def vertices : Fin 24 → R4 :=
  fun i =>
  match i with
  | 0 => (1,0,0,0)   | 1 => (-1,0,0,0)
  | 2 => (0,1,0,0)   | 3 => (0,-1,0,0)
  | 4 => (0,0,1,0)   | 5 => (0,0,-1,0)
  | 6 => (0,0,0,1)   | 7 => (0,0,0,-1)
  | 8  => (0.5,0.5,0.5,0.5)   | 9  => (0.5,0.5,0.5,-0.5)
  | 10 => (0.5,0.5,-0.5,0.5)  | 11 => (0.5,0.5,-0.5,-0.5)
  | 12 => (0.5,-0.5,0.5,0.5)  | 13 => (0.5,-0.5,0.5,-0.5)
  | 14 => (0.5,-0.5,-0.5,0.5) | 15 => (0.5,-0.5,-0.5,-0.5)
  | 16 => (-0.5,0.5,0.5,0.5)  | 17 => (-0.5,0.5,0.5,-0.5)
  | 18 => (-0.5,0.5,-0.5,0.5) | 19 => (-0.5,0.5,-0.5,-0.5)
  | 20 => (-0.5,-0.5,0.5,0.5) | 21 => (-0.5,-0.5,0.5,-0.5)
  | 22 => (-0.5,-0.5,-0.5,0.5)| 23 => (-0.5,-0.5,-0.5,-0.5)
  | _ => (0,0,0,0)

def q (i : Fin 24) : ℝ :=
  let (x, y, z, w) := vertices i
  let neg := (if x < 0 then 1 else 0) + (if y < 0 then 1 else 0) +
             (if z < 0 then 1 else 0) + (if w < 0 then 1 else 0)
  if neg % 2 = 0 then 1 else -1

abbrev H_D4 := Fin 24 → ℂ

def dulaPerturbation : Matrix (Fin 24) (Fin 24) ℂ :=
  Matrix.of (fun i j => ((q i * q j : ℝ) : ℂ))

lemma dula_trace_conserved :
    Matrix.trace dulaPerturbation = 24 := by
      -- By definition of $dulaPerturbation$, we know that its diagonal elements are all $1$.
      have h_diag : ∀ i : Fin 24, dulaPerturbation i i = 1 := by
        -- By definition of $dulaPerturbation$, we know that $dulaPerturbation i i = q i * q i$.
        simp [dulaPerturbation];
        unfold q; aesop;
      norm_num [ Matrix.trace, h_diag ]   -- 24 × 1 = 24

open BigOperators

lemma dula_null_zone :
    ∑ i : Fin 24, ∑ j : Fin 24, (dulaPerturbation i j) = 0 := by
      -- The sum of all entries in the matrix is the square of the sum of the q values.
      have h_sum_sq : ∑ i : Fin 24, ∑ j : Fin 24, dulaPerturbation i j = (∑ i : Fin 24, q i) ^ 2 := by
        -- By definition of $dulaPerturbation$, we have $dulaPerturbation i j = q i * q j$.
        have h_dulaPerturbation : ∀ i j, dulaPerturbation i j = q i * q j := by
          -- By definition of $dulaPerturbation$, we have $dulaPerturbation i j = (q i * q j : ℝ)$.
          simp [dulaPerturbation];
        simp +decide [ h_dulaPerturbation, Finset.mul_sum _ _ _, Finset.sum_mul, sq ];
        exact Finset.sum_comm;
      rw [ h_sum_sq ] ; norm_cast; norm_num [ Fin.sum_univ_succ, q ] ;
      -- Let's simplify the expression by evaluating each term individually.
      simp [vertices] at *;
      -- Let's simplify the expression by evaluating each term individually and combining like terms.
      norm_num at *

lemma dula_non_zero_eigenvalue :
    ∃ (v : H_D4), v ≠ 0 ∧ (Matrix.mulVec dulaPerturbation v) = 24 • v := by
      constructor;
      refine' ⟨ _, _ ⟩;
      rotate_right;
      exact fun i => ( q i : ℂ );
      · norm_num [ funext_iff ];
        exact ⟨ 0, by unfold q; unfold vertices; norm_num ⟩;
      · ext i; simp +decide [ dulaPerturbation, Matrix.mulVec ] ; ring; (
        norm_num [ dotProduct ] ; ring; norm_cast; (
        rw [ ← Finset.mul_sum _ _ _, Finset.sum_congr rfl fun _ _ => by rw [ show q _ ^ 2 = 1 by exact by unfold q; norm_num ] ] ; norm_num;););

lemma dula_twin_prime_eigenvalue :
    let one_vec : H_D4 := fun _ => (1 : ℂ)
    (Matrix.mulVec dulaPerturbation one_vec) = 0 • one_vec := by
      -- By definition of matrix multiplication, each entry in the resulting vector is the sum of the entries in the corresponding row of the matrix.
      have h_row_sum : ∀ i : Fin 24, ∑ j : Fin 24, dulaPerturbation i j = 0 := by
        -- We'll use that the sum of the entries in each row of the perturbation matrix is zero.
        have h_row_sum_zero : ∀ i, ∑ j, dulaPerturbation i j = q i * ∑ j, q j := by
          -- By definition of matrix multiplication, each entry in the resulting vector is the sum of the entries in the corresponding row of the matrix. Since the matrix is constructed such that each entry is q_i * q_j, the sum of the entries in the i-th row is q_i multiplied by the sum of all q_j's.
          intros i
          simp [dulaPerturbation];
          rw [ Finset.mul_sum _ _ _ ];
        -- Since the sum of the q values is zero, we can substitute this into the expression for the row sum.
        have h_sum_q_zero : ∑ j, q j = 0 := by
          unfold q; norm_cast; norm_num [ Fin.sum_univ_succ ] ;
          simp +decide [ vertices ] at * <;> norm_num at * <;> first | linarith | aesop | assumption;
        simp [h_row_sum_zero, h_sum_q_zero] at *;
      exact funext fun i => by simpa [ Matrix.mulVec, dotProduct ] using h_row_sum i;

#check dula_trace_conserved
#check dula_null_zone
#check dula_non_zero_eigenvalue
#check dula_twin_prime_eigenvalue

lemma q_sq_eq_one (i : Fin 24) : q i * q i = 1 := by
  -- By definition of $q$, we know that $q(i)$ is either $1$ or $-1$.
  have h_q_values : ∀ i : Fin 24, q i = 1 ∨ q i = -1 := by
    -- By definition of $q$, we know that $q(i)$ is either $1$ or $-1$ for all $i$.
    intros i
    simp [q];
    -- Since the sum of the if statements can only be 0, 1, 2, 3, or 4, it is always even or odd.
    by_cases h_even : (((((if (vertices i).1 < 0 then 1 else 0) + if (vertices i).2.1 < 0 then 1 else 0) + if (vertices i).2.2.1 < 0 then 1 else 0) + if (vertices i).2.2.2 < 0 then 1 else 0) % 2 = 0);
    · -- Since the sum is even, the first part of the disjunction is true.
      left; intro h_odd; exact absurd h_odd (by rw [h_even]; norm_num);
    · -- Since the sum is not even, it must be odd.
      simp [h_even];
  cases h_q_values i <;> simp +decide [ * ]

lemma sum_q_eq_zero : ∑ i : Fin 24, q i = 0 := by
  -- We can just evaluate the sum directly since it's a finite sum over 24 elements.
  -- Expanding the sum and evaluating q for each index should work.
  simp [q, vertices]
  norm_num
  -- If norm_num gets stuck, we might need to be more explicit, but let's try this first.
  -- Let's simplify the expression by evaluating each term individually and summing them up. We'll start by simplifying the innermost if statement and then work our way out.
  simp [Finset.univ] at *;
  -- Let's simplify the expression by evaluating each term individually and summing them up. We'll start by simplifying the innermost if statement and then work our way out. We'll use the fact that multiplication by a constant out of the sum can be taken outside.
  simp [Fintype.elems] at *;
  -- Let's simplify the expression by evaluating each term individually and summing them up. We'll start by simplifying the innermost if statement and then work our way out. We'll use the fact that multiplication by a constant out of the sum can be taken outside, and that the sum of a constant over a list is the constant times the length of the list.
  simp [List.finRange, List.length] at *;
  -- Let's simplify the expression by evaluating each term individually and summing them up. We'll start by simplifying the innermost if statement and then work our way out. We'll use the fact that multiplication by a constant out of the sum can be taken outside, and that the sum of a constant over a list is the constant times the length of the list. We'll also use the fact that the length of the list is 24.
  norm_num [List.length] at *

lemma dula_trace_conserved_proven :
    Matrix.trace dulaPerturbation = 24 := by
      -- Apply the lemma that states the trace of the Dula perturbation matrix is 24.
      apply dula_trace_conserved

lemma dula_null_zone_proven :
    ∑ i : Fin 24, ∑ j : Fin 24, (dulaPerturbation i j) = 0 := by
      -- Apply the lemma that states the sum of all entries in the matrix is zero.
      apply dula_null_zone

lemma dula_non_zero_eigenvalue_proven :
    ∃ (v : H_D4), v ≠ 0 ∧ (Matrix.mulVec dulaPerturbation v) = 24 • v := by
      -- Apply the lemma that states there exists a non-zero vector v such that dulaPerturbation.mulVec v = 24 • v.
      apply dula_non_zero_eigenvalue

lemma dula_twin_prime_eigenvalue_proven :
    let one_vec : H_D4 := fun _ => (1 : ℂ)
    (Matrix.mulVec dulaPerturbation one_vec) = 0 • one_vec := by
      -- Apply the lemma that states the multiplication of the dulaPerturbation matrix with the vector of ones results in the zero vector.
      apply dula_twin_prime_eigenvalue

lemma dula_trace_conserved_actual :
    Matrix.trace dulaPerturbation = 24 := by
      -- Apply the lemma that states the trace of the dulaPerturbation matrix is 24.
      apply dula_trace_conserved_proven