/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 4326851c-4406-4a31-80da-4030ee218157

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
I have successfully loaded the definitions of the 24-cell vertices, the DULA parity charge `q`, and the `dulaPerturbation` matrix. I have also formally verified the core lemmas: `dula_trace_conserved`, `dula_null_zone`, `dula_non_zero_eigenvalue`, and `dula_twin_prime_eigenvalue`. All proofs were completed automatically by the ATP.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open BigOperators

/-- 24-cell vertices (Hurwitz quaternions) -/
def vertices : Fin 24 → ℝ × ℝ × ℝ × ℝ :=
  fun i => match i with
  | 0 => (1, 0, 0, 0)   | 1 => (-1, 0, 0, 0)
  | 2 => (0, 1, 0, 0)   | 3 => (0, -1, 0, 0)
  | 4 => (0, 0, 1, 0)   | 5 => (0, 0, -1, 0)
  | 6 => (0, 0, 0, 1)   | 7 => (0, 0, 0, -1)
  | 8  => (0.5,0.5,0.5,0.5)   | 9  => (0.5,0.5,0.5,-0.5)
  | 10 => (0.5,0.5,-0.5,0.5)  | 11 => (0.5,0.5,-0.5,-0.5)
  | 12 => (0.5,-0.5,0.5,0.5)  | 13 => (0.5,-0.5,0.5,-0.5)
  | 14 => (0.5,-0.5,-0.5,0.5) | 15 => (0.5,-0.5,-0.5,-0.5)
  | 16 => (-0.5,0.5,0.5,0.5)  | 17 => (-0.5,0.5,0.5,-0.5)
  | 18 => (-0.5,0.5,-0.5,0.5) | 19 => (-0.5,0.5,-0.5,-0.5)
  | 20 => (-0.5,-0.5,0.5,0.5) | 21 => (-0.5,-0.5,0.5,-0.5)
  | 22 => (-0.5,-0.5,-0.5,0.5)| 23 => (-0.5,-0.5,-0.5,-0.5)
  | _ => (0, 0, 0, 0)

/-- DULA parity charge computed from sign pattern -/
def q (i : Fin 24) : ℝ :=
  let v := vertices i
  let neg := (if v.1 < 0 then 1 else 0) + (if v.2.1 < 0 then 1 else 0) +
             (if v.2.2.1 < 0 then 1 else 0) + (if v.2.2.2 < 0 then 1 else 0)
  if neg % 2 = 0 then 1 else -1

abbrev H_D4 := Fin 24 → ℂ

def dulaPerturbation : Matrix (Fin 24) (Fin 24) ℂ :=
  Matrix.of (fun i j => ((q i * q j : ℝ) : ℂ))

lemma dula_trace_conserved :
    Matrix.trace dulaPerturbation = 24 := by
      -- Since $q_i$ is either $1$ or $-1$, we have $q_i^2 = 1$ for all $i$.
      have h_q_sq : ∀ i : Fin 24, q i = 1 ∨ q i = -1 := by
        -- By definition of $q$, we know that $q_i$ is either $1$ or $-1$ for all $i$.
        intros i
        simp [q];
        -- By definition of $q$, we know that $q_i$ is either $1$ or $-1$ for all $i$. We can prove this by checking each case.
        cases' Nat.mod_two_eq_zero_or_one ( ( ( ( if ( vertices i |>.1 ) < 0 then 1 else 0 ) + if ( vertices i |>.2.1 ) < 0 then 1 else 0 ) + if ( vertices i |>.2.2.1 ) < 0 then 1 else 0 ) + if ( vertices i |>.2.2.2 ) < 0 then 1 else 0 ) with h h <;> simp [h];
      unfold dulaPerturbation; norm_num [ Finset.sum_range_succ, h_q_sq ] ; ring;
      erw [ Matrix.trace ] ; norm_cast ; norm_num [ Finset.sum_range_succ, h_q_sq ] ; ring;
      exact mod_cast by rw [ Finset.sum_congr rfl fun i hi => by rcases h_q_sq i with h | h <;> rw [ h ] ; norm_num ] ; norm_cast;      -- 24 × 1 = 24

lemma dula_null_zone :
    ∑ i, ∑ j, (dulaPerturbation i j) = 0 := by
      -- By definition of $dulaPerturbation$, we know that its trace is zero.
      simp [dulaPerturbation];
      unfold q; norm_num [ Fin.sum_univ_succ ] ;
      simp +decide [ vertices ] at *;
      norm_num [ Fin.ext_iff ] at *

lemma dula_non_zero_eigenvalue :
    ∃ (v : H_D4), v ≠ 0 ∧ (Matrix.mulVec dulaPerturbation v) = 24 • v := by
      -- Since the matrix is symmetric, it has real eigenvalues. The trace is 24, which is the sum of the eigenvalues. If all eigenvalues were less than 24, their sum would be less than 24*24, but since the trace is 24, there must be at least one eigenvalue that is 24. Therefore, there exists an eigenvector v such that dulaPerturbation.mulVec v = 24 • v.
      have h_eigenvalue : ∃ v : H_D4, v ≠ 0 ∧ dulaPerturbation.mulVec v = 24 • v := by
        have h_trace : Matrix.trace dulaPerturbation = 24 := by
          -- Apply the lemma that states the trace of the dulaPerturbation matrix is 24.
          apply dula_trace_conserved
        unfold dulaPerturbation at *; simp_all +decide [ Matrix.trace ] ;
        -- Since the sum of the squares of the q values is 24, we can take the vector v to be the vector where each component is q_i.
        use fun i => (q i : ℂ) / 24;
        simp_all +decide [ funext_iff, Matrix.mulVec, dotProduct ];
        simp_all +decide [ ← Finset.mul_sum _ _ _, ← Finset.sum_mul, mul_assoc, mul_div_cancel₀ ];
        simp_all +decide [ ← mul_div_assoc, ← Finset.sum_div ];
        exact ⟨ 0, by unfold q; unfold vertices; norm_num ⟩;
      exact h_eigenvalue

lemma dula_twin_prime_eigenvalue :
    let one_vec : H_D4 := fun _ => (1 : ℂ)
    (Matrix.mulVec dulaPerturbation one_vec) = 0 • one_vec := by
      -- By definition of $dulaPerturbation$, we know that each row sums to zero.
      have h_row_sum : ∀ i, ∑ j, dulaPerturbation i j = 0 := by
        intro i
        have h_sum : ∑ j, (dulaPerturbation i j) = (q i : ℝ) * ∑ j, (q j : ℝ) := by
          simp +decide [ dulaPerturbation, Finset.mul_sum _ _ _ ];
        rw [ h_sum ];
        norm_num [ Fin.sum_univ_succ, q ];
        norm_num [ Fin.succ, vertices ] at *;
      exact funext fun i => by simpa [ Matrix.mulVec, dotProduct ] using h_row_sum i;

#check dula_trace_conserved
#check dula_null_zone
#check dula_non_zero_eigenvalue
#check dula_twin_prime_eigenvalue