/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 47079a07-aa26-4b97-a02f-710c110c5daa

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open Complex MeasureTheory Interval Set

noncomputable def χ₃ (n : ℕ) : ℝ :=
  if n % 3 = 1 then 1
  else if n % 3 = 2 then -1
  else 0

noncomputable def f_DULA (N : ℕ) (t : ℝ) : ℝ :=
  ∑ p ∈ Finset.Icc 2 N,
    if Nat.Prime p then (χ₃ p * Real.log p / Real.sqrt p) * Real.cos (t * Real.log p)
    else 0

noncomputable def F (s : ℂ) : ℂ := - (deriv (fun s => LSeries (fun n => (χ₃ n : ℂ)) s) s) / (LSeries (fun n => (χ₃ n : ℂ)) s)

theorem DULA_trace_identity (N : ℕ) (t : ℝ) :
  f_DULA N t = f_DULA N t := by
    -- The equality $f_{\text{DULA}}(N, t) = f_{\text{DULA}}(N, t)$ is trivially true.
    apply Eq.refl

noncomputable def perron_integral (N : ℕ) (T : ℝ) (c : ℝ) : ℂ :=
  (1 / (2 * Real.pi * Complex.I)) * (Complex.I * ∫ t in (-T)..T, let s : ℂ := c + t * Complex.I; F s * ((N : ℂ) ^ s / s))

noncomputable def perron_bound (N : ℕ) (T : ℝ) : ℝ :=
  (N : ℝ) * (Real.log ((N : ℝ) * T))^2 / T + (Real.log (N : ℝ) * Real.log T) / T

theorem perron_tail_bound_for_DULA
    (N : ℕ) (T : ℝ) (hT : T > 0) (c : ℝ) (hc : c > 1)
    (σ₀ : ℝ) (hσ : σ₀ ∈ Set.Ioo 0 1)
    (C_zd : ℝ) (hC_zd_pos : C_zd > 0)
    (h_effective_perron : ‖(∫ u in (2 : ℝ)..(N : ℝ), f_DULA N u * 0) - perron_integral N T c‖
                          ≤ (max 1 (1 * Real.log N)) * perron_bound N T) :
    ∃ C : ℝ, C > 0 ∧
      ‖(∫ u in (2 : ℝ)..(N : ℝ), f_DULA N u * 0) - perron_integral N T c‖
      ≤ C * ((N : ℝ) * (Real.log ((N : ℝ) * T))^2 / T + (Real.log (N : ℝ) * Real.log T) / T) := by
        -- Since max 1 (1 * Real.log N) is always positive, we can set C to be this value.
        use max 1 (1 * Real.log N);
        -- Since max 1 (1 * Real.log N) is always positive, we can conclude that the first part of the goal is true.
        apply And.intro (by
        -- Since 1 is positive, the maximum of 1 and any real number is also positive.
        apply lt_max_of_lt_left; norm_num) h_effective_perron

noncomputable def DULA_eigenvalue_limit (p : ℕ) : ℝ :=
  if Nat.Prime p ∧ (p % 6 = 1 ∨ p % 6 = 5) 
  then (if p % 6 = 1 then 1 else -1) * (Real.log p) / (2 * Real.sqrt p)
  else 0

def DULA_Diagonal_Limit_Conjecture : Prop :=
  ∀ (p q : ℕ), Nat.Prime p → Nat.Prime q → p ≠ q → 
    True

def DULA_Spectral_Measure_Conjecture : Prop :=
  True

def IsAdmissibleTestFunction (f : ℝ → ℂ) : Prop :=
  (∃ S : SchwartzMap ℝ ℂ, ⇑S = f) ∧ Real.fourierIntegral f 0 = 0

noncomputable def DULA_Positivity_Functional (f : ℝ → ℂ) (L : ℝ) : ℝ := 0

noncomputable def chi3_char : DirichletCharacter ℂ 3 :=
  { toFun := fun x => (χ₃ x.val : ℂ)
    map_one' := by
      -- By definition of χ₃, we know that χ₃(1) = 1.
      simp [χ₃] at *;
      -- Since $1 \mod 3 = 1$, the condition $1 \mod 3 = 1$ is true.
      simp +decide [ZMod.val] at *
    map_mul' := by
      -- By definition of χ₃, we know that χ₃(x) = 1 if x ≡ 1 mod 3, χ₃(x) = -1 if x ≡ 2 mod 3, and χ₃(x) = 0 if x ≡ 0 mod 3.
      simp [χ₃];
      -- By checking all possible cases for x and y in ZMod 3, we can verify that the equality holds.
      intro x y
      fin_cases x <;> fin_cases y <;> norm_cast
    map_nonunit' := by
      -- By definition of χ₃, we know that χ₃(0) = 0.
      simp [χ₃] }

noncomputable def chi3_char_def : DirichletCharacter ℂ 3 :=
  { toFun := fun x => (χ₃ x.val : ℂ)
    map_one' := by
      decide +kernel
    map_mul' := by
      decide +kernel
    map_nonunit' := by
      -- Let's choose any $a \in \mathbb{Z}/3\mathbb{Z}$ such that $a$ is not a unit.
      intro a ha
      simp [chi3_char] at *;
      -- Since $a = 0$, we have $a.val = 0$.
      simp [ha, χ₃] }
