/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 5902f26b-ef7d-469e-98ac-d3faa29b74b6

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This file defines the Dula grading `psi_mod6` and the Dirichlet character `χ₃` modulo 3, and proves that they are equal for all natural numbers coprime to 6.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definitions for the Dula grading problem: χ₃ (character mod 3), M_mod6 (integers coprime to 6), m5_mod6 (count of prime factors congruent to 5 mod 6), and psi_mod6 (the Dula grading).
-/
def χ₃ (n : ℕ) : ℤ := if n % 3 = 1 then 1 else if n % 3 = 2 then -1 else 0

def M_mod6 : Set ℕ := {n | n.Coprime 6}

def m5_mod6 (n : ℕ) : ℕ := (n.primeFactorsList.filter (fun p => p % 6 = 5)).length

def psi_mod6 (n : ℕ) : ℤ := if Even (m5_mod6 n) then 1 else -1

/-
The Dula grading psi_mod6 (based on the parity of the number of prime factors congruent to 5 mod 6) is exactly the Dirichlet character χ₃ mod 3 for numbers coprime to 6.
-/
theorem dula_psi_is_chi3 (n : ℕ) (hn : n ∈ M_mod6) :
    psi_mod6 n = χ₃ n := by
      -- We'll use induction on $n$ to prove that $\psi_{6}(n) = \chi_{3}(n)$ for all $n \in M_{6}$.
      induction' n using Nat.strong_induction_on with n ih;
      by_cases h₂ : n = 1 ∨ Nat.Prime n ∨ ∃ a b, 1 < a ∧ 1 < b ∧ a * b = n ∧ a ∈ M_mod6 ∧ b ∈ M_mod6;
      · rcases h₂ with ( rfl | h₂ | ⟨ a, b, ha, hb, rfl, ha', hb' ⟩ ) <;> norm_num at *;
        · native_decide +revert;
        · rcases Nat.mod_lt n ( by decide : 6 > 0 ) with h₃ ; interval_cases _ : n % 6 <;> simp_all +decide [ ← Nat.dvd_iff_mod_eq_zero, h₂.dvd_iff_eq ] ;
          · unfold psi_mod6 χ₃;
            unfold m5_mod6; rw [ ← Nat.mod_mod_of_dvd n ( by decide : 3 ∣ 6 ), ‹n % 6 = _› ] ; norm_num;
            rw [ Nat.primeFactorsList_prime h₂ ] ; aesop;
          · have := Nat.Prime.eq_two_or_odd h₂; simp_all +decide [ ← Nat.mod_mod_of_dvd n ( by decide : 2 ∣ 6 ) ] ;
            exact absurd hn ( by unfold M_mod6; decide );
          · have := Nat.dvd_of_mod_eq_zero ( show n % 3 = 0 by norm_num [ ← Nat.mod_mod_of_dvd n ( by decide : 3 ∣ 6 ), * ] ) ; rw [ h₂.dvd_iff_eq ] at this <;> simp_all +decide ;
            exact absurd hn ( by unfold M_mod6; decide );
          · have := Nat.Prime.eq_two_or_odd h₂; omega;
          · unfold psi_mod6 χ₃;
            unfold m5_mod6; simp_all +decide [ ← Nat.mod_mod_of_dvd n ( by decide : 3 ∣ 6 ) ] ;
            rw [ Nat.primeFactorsList_prime h₂ ] ; aesop;
        · -- By definition of $psi_mod6$, we have $psi_mod6 (a * b) = psi_mod6 a * psi_mod6 b$.
          have h_psi_mul : psi_mod6 (a * b) = psi_mod6 a * psi_mod6 b := by
            unfold psi_mod6;
            unfold m5_mod6; simp +decide [ Nat.primeFactorsList, List.filter_append ] ;
            -- By definition of prime factors list, we can split the list into the concatenation of the prime factors lists of $a$ and $b$.
            have h_prime_factors : (a * b).primeFactorsList.Perm (a.primeFactorsList ++ b.primeFactorsList) := by
              rw [ List.perm_iff_count ];
              intro p; by_cases hp : p.Prime <;> simp_all +decide [ Nat.primeFactorsList ] ;
              rw [ Nat.factorization_mul ] <;> aesop;
            have := h_prime_factors.filter ( fun p => p % 6 = 5 ) ; simp_all +decide [ List.Perm.length_eq ] ;
            have := this.length_eq; simp_all +decide [ parity_simps ] ;
            grind +ring;
          rw [ h_psi_mul, ih a ( by nlinarith ) ha', ih b ( by nlinarith ) hb' ];
          unfold χ₃; norm_num [ Nat.mul_mod ] ; have := Nat.mod_lt a zero_lt_three; have := Nat.mod_lt b zero_lt_three; interval_cases a % 3 <;> interval_cases b % 3 <;> trivial;
      · rcases n with ( _ | _ | n ) <;> simp_all +decide [ M_mod6 ];
        contrapose! h₂;
        intro h; rcases Nat.exists_dvd_of_not_prime2 ( by linarith ) h with ⟨ k, hk₁, hk₂ ⟩ ; use k, by nlinarith, ( n + 1 + 1 ) / k, by nlinarith [ Nat.div_mul_cancel hk₁ ], by rw [ Nat.mul_div_cancel' hk₁ ], ?_, ?_ <;> simp_all +decide [ Nat.Coprime, Nat.gcd_mul_left ] ;
        · exact Nat.Coprime.coprime_dvd_left hk₁ hn;
        · exact Nat.Coprime.coprime_dvd_left ( Nat.div_dvd_of_dvd hk₁ ) hn

/-
The Dula grading recovers the character χ₃ for all n coprime to 6.
-/
theorem dula_grading_recovers_chi3 :
    ∀ n ∈ M_mod6, psi_mod6 n = χ₃ n := by
      exact?
