/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 9af37861-cddf-4639-8da1-a4f0bf10e296

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module defines the Dynamic Prime Inertia Engine (PIE) Operator and related structures.
It includes definitions for the dynamic kernel, the Leech kernel, and their spectral properties.
It proves convergence, symmetry, and boundedness of the kernels, and establishes the ensemble averaging properties.
The final theorem `RH_iff_PIE_spectrum` equating the Riemann Hypothesis to the operator's spectral alignment is formalized as `RH_iff_PIE_spectrum_statement`, but remains an open problem (the Riemann Hypothesis) and is not proven here.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

def chi6 (n : ℤ) : ℝ :=
  if n % 6 = 1 then 1
  else if n % 6 = 5 then -1
  else 0

lemma chi6_abs_le_one (n : ℤ) : |chi6 n| ≤ 1 := by
  simp [chi6]; split_ifs <;> norm_num

def is_prime_mod6 (p : ℕ) : Prop := Nat.Prime p ∧ (p % 6 = 1 ∨ p % 6 = 5)

noncomputable def DULA_dynamic_kernel_inf_v2 (t θ x y : ℝ) : ℝ :=
  ∑' (p : {p // is_prime_mod6 p}),
    chi6 p * (Real.log p / (p : ℝ) ^ 2) *
    Real.cos (t * Real.log p + θ) *
    Real.cos (Real.log p * (x - y))

theorem summable_DULA_dynamic_kernel_term_v2 (t θ x y : ℝ) :
    Summable fun (p : {p // is_prime_mod6 p}) =>
      |chi6 p * (Real.log p / (p : ℝ) ^ 2) * Real.cos (t * Real.log p + θ) * Real.cos (Real.log p * (x - y))| := by
  -- We know \(\log n \le \sqrt{n}\) for large \(n\), so \(\frac{\log n}{n^2} \le \frac{1}{n^{1.5}}\).
  have h_log_bound : ∀ n : ℕ, n ≥ 2 → Real.log n / n^2 ≤ 1 / n^(3/2 : ℝ) := by
    intro n hn; rw [ div_le_div_iff₀ ] <;> try positivity;
    -- We'll use the fact that \(\log n \leq \sqrt{n}\) for all \(n \geq 2\).
    have h_log_le_sqrt : ∀ n : ℕ, 2 ≤ n → Real.log n ≤ Real.sqrt n := by
      intro n hn; have := Real.log_le_sub_one_of_pos ( by positivity : 0 < Real.sqrt n / 2 ) ; rw [ Real.log_div ( by positivity ) ( by positivity ), Real.log_sqrt ( by positivity ) ] at this; ring_nf at *; norm_num at *; nlinarith [ Real.log_le_sub_one_of_pos zero_lt_two, Real.log_pos one_lt_two, Real.sqrt_nonneg n, Real.sq_sqrt <| Nat.cast_nonneg n, ( by norm_cast : ( 2 :ℝ ) ≤ n ) ] ;
    exact le_trans ( mul_le_mul_of_nonneg_right ( h_log_le_sqrt n hn ) ( by positivity ) ) ( by rw [ Real.sqrt_eq_rpow ] ; rw [ ← Real.rpow_natCast, ← Real.rpow_add ( by positivity ) ] ; norm_num );
  -- Since \(\sum \frac{1}{n^{1.5}}\) converges (p-series with \(p > 1\)), the original series converges.
  have h_series_conv : Summable (fun p : ℕ => Real.log p / p^2) := by
    exact Summable.of_nonneg_of_le ( fun n => by positivity ) ( fun n => if hn : n < 2 then by interval_cases n <;> norm_num else h_log_bound n <| le_of_not_gt hn ) <| Real.summable_one_div_nat_rpow.2 <| by norm_num;
  refine' Summable.of_nonneg_of_le ( fun p => abs_nonneg _ ) ( fun p => _ ) ( h_series_conv.comp_injective Subtype.coe_injective );
  norm_num [ abs_mul ];
  refine' le_trans ( mul_le_of_le_one_right ( by positivity ) ( Real.abs_cos_le_one _ ) ) _;
  exact le_trans ( mul_le_of_le_one_right ( by positivity ) ( Real.abs_cos_le_one _ ) ) ( le_trans ( mul_le_of_le_one_left ( by positivity ) ( chi6_abs_le_one _ ) ) ( le_of_eq ( abs_of_nonneg ( by positivity ) ) ) )

theorem DULA_dynamic_kernel_inf_symmetric (t θ x y : ℝ) :
    DULA_dynamic_kernel_inf_v2 t θ x y = DULA_dynamic_kernel_inf_v2 t θ y x := by
      -- By definition of \(DULA_dynamic_kernel_inf\), we can see that the sum is symmetric in \(x\) and \(y\) because the cosine function is even.
      simp [DULA_dynamic_kernel_inf_v2, Real.cos_neg];
      -- Since the cosine function is even, we have Real.cos (Real.log p * (y - x)) = Real.cos (Real.log p * (x - y)).
      have h_cos_even : ∀ p : {p // is_prime_mod6 p}, Real.cos (Real.log p * (y - x)) = Real.cos (Real.log p * (x - y)) := by
        -- Since the cosine function is even, we have \(\cos(-θ) = \cos(θ)\) for any angle \(θ\).
        intros p
        rw [←Real.cos_neg]
        ring;
      -- Apply the equality of the cosine terms to each term in the sum.
      simp [h_cos_even]

theorem DULA_dynamic_kernel_inf_bounded (t θ : ℝ) :
    ∃ C : ℝ, ∀ x y : ℝ, |DULA_dynamic_kernel_inf_v2 t θ x y| ≤ C := by
      use ∑' p : {p // is_prime_mod6 p}, |chi6 p * (Real.log p / (p : ℝ) ^ 2)|;
      intro x y
      have h_abs_conv : Summable (fun p : {p // is_prime_mod6 p} => |chi6 p * (Real.log p / (p : ℝ) ^ 2)|) := by
        have := summable_DULA_dynamic_kernel_term_v2 0 0 0 0; aesop;
      refine' le_trans ( le_of_eq <| by rw [ DULA_dynamic_kernel_inf_v2 ] ) ( le_trans ( ( le_of_eq <| by rw [ ← Real.norm_eq_abs ] ) ) ( le_trans ( norm_tsum_le_tsum_norm _ ) _ ) );
      · exact?;
      · refine' Summable.tsum_le_tsum _ _ h_abs_conv;
        · norm_num [ abs_div, abs_mul ];
          exact fun p hp => mul_le_of_le_one_right ( by positivity ) ( Real.abs_cos_le_one _ ) |> le_trans <| mul_le_of_le_one_right ( by positivity ) ( Real.abs_cos_le_one _ ) ;
        · simp +zetaDelta at *;
          exact Summable.of_nonneg_of_le ( fun _ => by positivity ) ( fun _ => mul_le_of_le_one_right ( by positivity ) ( Real.abs_cos_le_one _ ) |> le_trans <| mul_le_of_le_one_right ( by positivity ) ( Real.abs_cos_le_one _ ) ) <| h_abs_conv.congr fun _ => by norm_num [ abs_div, abs_mul ] ;

noncomputable def H_DULA_dynamic_inf (L : ℝ) (t θ : ℝ) (f : ℝ → ℝ) : ℝ → ℝ :=
  fun x => ∫ y in Set.Icc 0 L, DULA_dynamic_kernel_inf_v2 t θ x y * f y

noncomputable def H_DULA_ensemble_inf (L : ℝ) (M : ℕ) (t : ℝ) (f : ℝ → ℝ) : ℝ → ℝ :=
  fun x => (1 / (M : ℝ)) * ∑ k ∈ Finset.range M,
    H_DULA_dynamic_inf L t ((k : ℝ) * 2 * Real.pi / (M : ℝ)) f x

noncomputable def Leech_min_norm : ℝ := 4

noncomputable def Leech_scale : ℝ := Real.sqrt Leech_min_norm

noncomputable def DULA_dynamic_kernel_leech_inf_v2 (t θ x y : ℝ) : ℝ :=
  ∑' (p : {p // is_prime_mod6 p}),
    chi6 p * (Real.log p / (p : ℝ) ^ 2) *
    Real.cos (t * Real.log p * Leech_scale + θ) *
    Real.cos (Real.log p * (x - y))

theorem summable_DULA_dynamic_kernel_leech_term_v2 (t θ x y : ℝ) :
    Summable fun (p : {p // is_prime_mod6 p}) =>
      |chi6 p * (Real.log p / (p : ℝ) ^ 2) * Real.cos (t * Real.log p * Leech_scale + θ) * Real.cos (Real.log p * (x - y))| := by
  field_simp;
  -- We'll use the fact that |chi6(p)| ≤ 1 and |cos| ≤ 1 for all p.
  have h_bound : ∀ p : { p : ℕ // is_prime_mod6 p }, |(chi6 p) * (Real.log p) * (Real.cos (Real.log p * t * Leech_scale + θ)) * (Real.cos (Real.log p * (x - y))) / (p : ℝ) ^ 2| ≤ (Real.log p) / (p : ℝ) ^ 2 := by
    norm_num [ abs_div, abs_mul ];
    intro p hp; gcongr;
    refine' le_trans ( mul_le_of_le_one_right ( by positivity ) ( Real.abs_cos_le_one _ ) ) _;
    refine' le_trans ( mul_le_of_le_one_right ( by positivity ) ( Real.abs_cos_le_one _ ) ) _;
    rw [ abs_of_nonneg ( Real.log_nonneg ( Nat.one_le_cast.mpr hp.1.pos ) ) ] ; exact mul_le_of_le_one_left ( Real.log_nonneg ( Nat.one_le_cast.mpr hp.1.pos ) ) ( chi6_abs_le_one _ ) ;
  refine' Summable.of_nonneg_of_le ( fun p => abs_nonneg _ ) ( fun p => h_bound p ) _;
  -- We'll use the fact that \(\sum_{p \equiv 1, 5 \pmod{6}} \frac{\log p}{p^2}\) converges.
  have h_summable : Summable (fun p : ℕ => (Real.log p) / (p : ℝ) ^ 2) := by
    -- We can compare our series with the convergent p-series \(\sum_{p=1}^{\infty} \frac{1}{p^{3/2}}\).
    have h_compare : ∀ p : ℕ, p ≥ 2 → (Real.log p) / (p : ℝ) ^ 2 ≤ 1 / (p : ℝ) ^ (3 / 2 : ℝ) := by
      intro p hp
      have : Real.log p ≤ Real.sqrt p := by
        have := Real.log_le_sub_one_of_pos ( by positivity : 0 < Real.sqrt p / 2 );
        rw [ Real.log_div ( by positivity ) ( by positivity ), Real.log_sqrt ( by positivity ) ] at this ; linarith [ Real.log_le_sub_one_of_pos zero_lt_two ] ;
      rw [ div_le_div_iff₀ ] <;> try positivity;
      exact le_trans ( mul_le_mul_of_nonneg_right this <| by positivity ) <| by rw [ Real.sqrt_eq_rpow, ← Real.rpow_natCast, ← Real.rpow_add <| by positivity ] ; norm_num;
    exact Summable.of_nonneg_of_le ( fun p => by positivity ) ( fun p => if hp : p < 2 then by interval_cases p <;> norm_num else h_compare p ( le_of_not_gt hp ) ) ( Real.summable_one_div_nat_rpow.2 ( by norm_num ) );
  exact h_summable.comp_injective Subtype.coe_injective

theorem DULA_dynamic_kernel_leech_inf_symmetric_v2 (t θ x y : ℝ) :
    DULA_dynamic_kernel_leech_inf_v2 t θ x y = DULA_dynamic_kernel_leech_inf_v2 t θ y x := by
      -- The symmetry of the kernel follows from the symmetry of the cosine function.
      simp [DULA_dynamic_kernel_leech_inf_v2, Real.cos_sub];
      -- Since the cosine function is even, we have \(\cos(\log p \cdot (x - y)) = \cos(\log p \cdot (y - x))\).
      have h_cos_even : ∀ p : {p : ℕ // is_prime_mod6 p}, Real.cos (Real.log p * (x - y)) = Real.cos (Real.log p * (y - x)) := by
        -- Since the cosine function is even, we have \(\cos(-\theta) = \cos(\theta)\).
        intros p
        rw [←Real.cos_neg]
        ring;
      -- Since the cosine function is even, we can replace \(\cos(\log p \cdot (x - y))\) with \(\cos(\log p \cdot (y - x))\) in the sum.
      simp [h_cos_even]

theorem DULA_dynamic_kernel_leech_inf_bounded_v2 (t θ : ℝ) :
    ∃ C : ℝ, ∀ x y : ℝ, |DULA_dynamic_kernel_leech_inf_v2 t θ x y| ≤ C := by
      -- The sum of the absolute values of the terms in the kernel is bounded.
      have h_abs_sum_bounded : ∃ C : ℝ, ∀ x y : ℝ, ∑' (p : {p // is_prime_mod6 p}),
            |chi6 p * (Real.log p / (p : ℝ) ^ 2) * Real.cos (t * Real.log p * Leech_scale + θ) * Real.cos (Real.log p * (x - y))| ≤ C := by
              use ∑' p : {p // is_prime_mod6 p}, |chi6 p * (Real.log p / (p : ℝ) ^ 2)|;
              field_simp;
              intro x y; refine' Summable.tsum_le_tsum _ _ _;
              · norm_num [ abs_div, abs_mul ];
                exact fun a ha => mul_le_mul_of_nonneg_right ( mul_le_of_le_one_right ( by positivity ) ( Real.abs_cos_le_one _ ) |> le_trans <| mul_le_of_le_one_right ( by positivity ) ( Real.abs_cos_le_one _ ) ) ( by positivity );
              · convert summable_DULA_dynamic_kernel_leech_term_v2 t θ x y using 2 ; norm_num [ abs_div, abs_mul ] ; ring;
              · have := summable_DULA_dynamic_kernel_leech_term_v2 0 0 0 0;
                simpa [ mul_div_assoc ] using this;
      refine' ⟨ h_abs_sum_bounded.choose, fun x y => le_trans ( _ : _ ≤ _ ) ( h_abs_sum_bounded.choose_spec x y ) ⟩;
      -- The absolute value of a sum is less than or equal to the sum of the absolute values.
      have h_abs_sum : ∀ {f : {p : ℕ // is_prime_mod6 p} → ℝ}, Summable (fun p => |f p|) → |∑' p, f p| ≤ ∑' p, |f p| := by
        intro f hf; convert norm_tsum_le_tsum_norm _ <;> tauto;
      exact h_abs_sum <| summable_DULA_dynamic_kernel_leech_term_v2 t θ x y

noncomputable def H_DULA_dynamic_leech_inf (L : ℝ) (t θ : ℝ) (f : ℝ → ℝ) : ℝ → ℝ :=
  fun x => ∫ y in Set.Icc 0 L, DULA_dynamic_kernel_leech_inf_v2 t θ x y * f y

noncomputable def H_DULA_ensemble_leech_inf (L : ℝ) (M : ℕ) (t : ℝ) (f : ℝ → ℝ) : ℝ → ℝ :=
  fun x => (1 / (M : ℝ)) * ∑ k ∈ Finset.range M,
    H_DULA_dynamic_leech_inf L t ((k : ℝ) * 2 * Real.pi / (M : ℝ)) f x

noncomputable def zeta_zeros_imag : Set ℝ := { μ | μ > 0 ∧ riemannZeta (1/2 + μ * Complex.I) = 0 }

noncomputable def spectrum_dynamic_inf (L : ℝ) (t θ : ℝ) : Set ℝ :=
  { μ | ∃ ψ : ℝ → ℝ,
      MeasureTheory.MemLp ψ 2 (MeasureTheory.Measure.restrict MeasureTheory.volume (Set.Icc 0 L)) ∧
      (∀ x ∈ Set.Icc 0 L, H_DULA_dynamic_inf L t θ ψ x = μ * ψ x) ∧
      ¬ (ψ =ᵐ[MeasureTheory.Measure.restrict MeasureTheory.volume (Set.Icc 0 L)] 0) }

theorem H_DULA_ensemble_inf_eq_averaged_kernel (L : ℝ) (M : ℕ) (hM : M > 0) (t : ℝ) (f : ℝ → ℝ)
    (hf : MeasureTheory.Integrable f (MeasureTheory.Measure.restrict MeasureTheory.volume (Set.Icc 0 L))) :
    ∀ x, H_DULA_ensemble_inf L M t f x =
      ∫ y in Set.Icc 0 L, ((1 / (M : ℝ)) * ∑ k ∈ Finset.range M, DULA_dynamic_kernel_inf_v2 t ((k : ℝ) * 2 * Real.pi / (M : ℝ)) x y) * f y := by
  -- By definition of $H_DULA_ensemble_inf$, we can write it as an integral over $y$ for each $x$.
  intro x
  simp [H_DULA_ensemble_inf, H_DULA_dynamic_inf];
  -- By the linearity of the integral, we can interchange the sum and the integral.
  have h_interchange : ∫ y in Set.Icc 0 L, ∑ k ∈ Finset.range M, DULA_dynamic_kernel_inf_v2 t (k * 2 * Real.pi / M) x y * f y = ∑ k ∈ Finset.range M, ∫ y in Set.Icc 0 L, DULA_dynamic_kernel_inf_v2 t (k * 2 * Real.pi / M) x y * f y := by
    -- Since the dynamic kernel is bounded and f is integrable, their product is integrable.
    have h_integrable : ∀ k ∈ Finset.range M, MeasureTheory.Integrable (fun y => DULA_dynamic_kernel_inf_v2 t ((k : ℝ) * 2 * Real.pi / M) x y * f y) (MeasureTheory.MeasureSpace.volume.restrict (Set.Icc 0 L)) := by
      intro k hk
      have h_bounded : ∃ C, ∀ y ∈ Set.Icc 0 L, |DULA_dynamic_kernel_inf_v2 t ((k : ℝ) * 2 * Real.pi / M) x y| ≤ C := by
        exact DULA_dynamic_kernel_inf_bounded t _ |> fun ⟨ C, hC ⟩ => ⟨ C, fun y hy => hC x y ⟩
      obtain ⟨C, hC⟩ := h_bounded
      have h_integrable : MeasureTheory.Integrable (fun y => C * |f y|) (MeasureTheory.MeasureSpace.volume.restrict (Set.Icc 0 L)) := by
        exact hf.norm.const_mul _
      have h_integrable : MeasureTheory.Integrable (fun y => DULA_dynamic_kernel_inf_v2 t ((k : ℝ) * 2 * Real.pi / M) x y * f y) (MeasureTheory.MeasureSpace.volume.restrict (Set.Icc 0 L)) := by
        refine' h_integrable.mono' _ _;
        · refine' MeasureTheory.AEStronglyMeasurable.mul _ hf.1;
          refine' Continuous.aestronglyMeasurable _;
          refine' continuous_tsum _ _ _;
          use fun n => |chi6 n| * ( Real.log n / n ^ 2 ) * 1 * 1;
          · fun_prop (disch := norm_num);
          · have h_summable : Summable (fun n : ℕ => |chi6 n| * (Real.log n / n ^ 2)) := by
              have h_summable : Summable (fun n : ℕ => (Real.log n / n ^ 2)) := by
                -- We can compare our series with the convergent p-series $\sum_{n=1}^{\infty} \frac{1}{n^{3/2}}$.
                have h_compare : ∀ n : ℕ, n ≥ 2 → (Real.log n) / (n : ℝ) ^ 2 ≤ 1 / (n : ℝ) ^ (3 / 2 : ℝ) := by
                  intro n hn
                  have : Real.log n ≤ Real.sqrt n := by
                    have := Real.log_le_sub_one_of_pos ( by positivity : 0 < Real.sqrt n / 2 );
                    rw [ Real.log_div ( by positivity ) ( by positivity ), Real.log_sqrt ( by positivity ) ] at this ; linarith [ Real.log_le_sub_one_of_pos zero_lt_two ] ;
                  rw [ div_le_div_iff₀ ] <;> try positivity;
                  exact le_trans ( mul_le_mul_of_nonneg_right this <| by positivity ) <| by rw [ Real.sqrt_eq_rpow, ← Real.rpow_natCast, ← Real.rpow_add <| by positivity ] ; norm_num;
                exact Summable.of_nonneg_of_le ( fun n => by positivity ) ( fun n => if hn : n < 2 then by interval_cases n <;> norm_num else h_compare n ( le_of_not_gt hn ) ) ( Real.summable_one_div_nat_rpow.2 ( by norm_num ) );
              exact Summable.of_nonneg_of_le ( fun n => mul_nonneg ( abs_nonneg _ ) ( div_nonneg ( Real.log_natCast_nonneg _ ) ( sq_nonneg _ ) ) ) ( fun n => mul_le_of_le_one_left ( div_nonneg ( Real.log_natCast_nonneg _ ) ( sq_nonneg _ ) ) ( by unfold chi6; split_ifs <;> norm_num ) ) h_summable;
            simpa using h_summable.comp_injective Subtype.coe_injective;
          · norm_num [ abs_mul, abs_div, abs_of_nonneg, Real.log_nonneg, Nat.cast_nonneg ];
            intro a ha x; rw [ abs_of_nonneg ( Real.log_natCast_nonneg a ) ] ; exact mul_le_of_le_one_right ( by positivity ) ( Real.abs_cos_le_one _ ) |> le_trans <| mul_le_of_le_one_right ( by positivity ) ( Real.abs_cos_le_one _ ) ;
        · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Icc ] with y hy using by simpa only [ Real.norm_eq_abs, abs_mul ] using mul_le_mul_of_nonneg_right ( hC y hy ) ( abs_nonneg _ ) ;
      exact h_integrable;
    exact MeasureTheory.integral_finset_sum _ fun k hk => h_integrable k hk;
  simp_all +decide [ mul_assoc, MeasureTheory.integral_const_mul ];
  simp_all +decide [ Finset.sum_mul _ _ _ ]

noncomputable def spectrum_dynamic_leech_inf (L : ℝ) (t θ : ℝ) : Set ℝ :=
  { μ | ∃ ψ : ℝ → ℝ,
      MeasureTheory.MemLp ψ 2 (MeasureTheory.Measure.restrict MeasureTheory.volume (Set.Icc 0 L)) ∧
      (∀ x ∈ Set.Icc 0 L, H_DULA_dynamic_leech_inf L t θ ψ x = μ * ψ x) ∧
      ¬ (ψ =ᵐ[MeasureTheory.Measure.restrict MeasureTheory.volume (Set.Icc 0 L)] 0) }

theorem H_DULA_ensemble_leech_inf_eq_averaged_kernel (L : ℝ) (M : ℕ) (hM : M > 0) (t : ℝ) (f : ℝ → ℝ)
    (hf : MeasureTheory.Integrable f (MeasureTheory.Measure.restrict MeasureTheory.volume (Set.Icc 0 L))) :
    ∀ x, H_DULA_ensemble_leech_inf L M t f x =
      ∫ y in Set.Icc 0 L, ((1 / (M : ℝ)) * ∑ k ∈ Finset.range M, DULA_dynamic_kernel_leech_inf_v2 t ((k : ℝ) * 2 * Real.pi / (M : ℝ)) x y) * f y := by
  -- By definition of $H_DULA_ensemble_leech_inf$, we can write it as an integral of the product of the dynamic kernel and $f$.
  intro x
  simp [H_DULA_ensemble_leech_inf, H_DULA_dynamic_leech_inf];
  -- Since the dynamic kernel is bounded, the product of the dynamic kernel and f is integrable.
  have h_integrable : ∀ k ∈ Finset.range M, MeasureTheory.Integrable (fun y => DULA_dynamic_kernel_leech_inf_v2 t ((k : ℝ) * 2 * Real.pi / M) x y * f y) (MeasureTheory.MeasureSpace.volume.restrict (Set.Icc 0 L)) := by
    intro k hk
    have h_bounded : ∃ C : ℝ, ∀ y ∈ Set.Icc 0 L, |DULA_dynamic_kernel_leech_inf_v2 t ((k : ℝ) * 2 * Real.pi / M) x y| ≤ C := by
      exact DULA_dynamic_kernel_leech_inf_bounded_v2 t ( ( k : ℝ ) * 2 * Real.pi / M ) |> fun ⟨ C, hC ⟩ => ⟨ C, fun y hy => hC x y ⟩
    obtain ⟨C, hC⟩ := h_bounded
    have h_integrable : MeasureTheory.Integrable (fun y => C * |f y|) (MeasureTheory.MeasureSpace.volume.restrict (Set.Icc 0 L)) := by
      exact hf.norm.const_mul _
    have h_integrable : MeasureTheory.Integrable (fun y => DULA_dynamic_kernel_leech_inf_v2 t ((k : ℝ) * 2 * Real.pi / M) x y * f y) (MeasureTheory.MeasureSpace.volume.restrict (Set.Icc 0 L)) := by
      refine' h_integrable.mono' _ _;
      · -- The product of measurable functions is measurable.
        have h_measurable : MeasureTheory.AEStronglyMeasurable (fun y => DULA_dynamic_kernel_leech_inf_v2 t ((k : ℝ) * 2 * Real.pi / M) x y) (MeasureTheory.MeasureSpace.volume.restrict (Set.Icc 0 L)) := by
          refine' Continuous.aestronglyMeasurable _;
          refine' continuous_tsum _ _ _;
          use fun p => |chi6 p| * ( Real.log p / p ^ 2 ) * 1 * 1;
          · fun_prop (disch := norm_num);
          · have h_summable : Summable (fun p : ℕ => |chi6 p| * (Real.log p / p ^ 2)) := by
              have h_summable : Summable (fun p : ℕ => (Real.log p / p ^ 2)) := by
                -- We can compare our series with the convergent p-series $\sum_{p=1}^{\infty} \frac{1}{p^{3/2}}$.
                have h_compare : ∀ p : ℕ, p ≥ 2 → Real.log p / p ^ 2 ≤ 1 / p ^ (3 / 2 : ℝ) := by
                  intro p hp
                  have : Real.log p ≤ p ^ (1 / 2 : ℝ) := by
                    rw [ ← Real.sqrt_eq_rpow ];
                    have := Real.log_le_sub_one_of_pos ( by positivity : 0 < Real.sqrt p / 2 );
                    rw [ Real.log_div ( by positivity ) ( by positivity ), Real.log_sqrt ( by positivity ) ] at this ; linarith [ Real.log_le_sub_one_of_pos zero_lt_two ] ;
                  field_simp;
                  exact le_trans ( mul_le_mul_of_nonneg_right this ( by positivity ) ) ( by rw [ ← Real.rpow_natCast, ← Real.rpow_add ( by positivity ) ] ; norm_num );
                exact Summable.of_nonneg_of_le ( fun p => by positivity ) ( fun p => if hp : p < 2 then by interval_cases p <;> norm_num else h_compare p ( le_of_not_gt hp ) ) ( Real.summable_one_div_nat_rpow.2 ( by norm_num ) );
              exact Summable.of_nonneg_of_le ( fun p => mul_nonneg ( abs_nonneg _ ) ( div_nonneg ( Real.log_natCast_nonneg _ ) ( sq_nonneg _ ) ) ) ( fun p => mul_le_of_le_one_left ( div_nonneg ( Real.log_natCast_nonneg _ ) ( sq_nonneg _ ) ) ( show |chi6 p| ≤ 1 from by unfold chi6; split_ifs <;> norm_num ) ) h_summable;
            simpa using h_summable.comp_injective Subtype.coe_injective;
          · norm_num [ abs_mul, abs_div, abs_of_nonneg, Real.log_nonneg ];
            intro a ha x; rw [ abs_of_nonneg ( Real.log_nonneg ( Nat.one_le_cast.mpr ( Nat.Prime.pos ha.1 ) ) ) ] ; exact mul_le_of_le_one_right ( by positivity ) ( Real.abs_cos_le_one _ ) |> le_trans <| mul_le_of_le_one_right ( by positivity ) ( Real.abs_cos_le_one _ ) ;
        exact h_measurable.mul hf.1;
      · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Icc ] with y hy using by simpa only [ Real.norm_eq_abs, abs_mul ] using mul_le_mul_of_nonneg_right ( hC y hy ) ( abs_nonneg _ ) ;
    exact h_integrable;
  simp +decide only [mul_assoc, Finset.mul_sum _ _ _, Finset.sum_mul];
  rw [ MeasureTheory.integral_finset_sum _ fun i hi => MeasureTheory.Integrable.const_mul ( by simpa only [ mul_assoc ] using h_integrable i hi ) _ ] ; simp +decide [ mul_assoc, MeasureTheory.integral_const_mul ]

#check Complex.re

#check spectrum_dynamic_leech_inf

#check riemannZeta

def RH_iff_PIE_spectrum_statement : Prop :=
  (∀ s : ℂ, riemannZeta s = 0 ∧ 0 < s.re ∧ s.re < 1 → s.re = 1/2) →
  ∀ L M : ℕ, ∀ t : ℝ, (0 < L) ∧ (0 < M) →
    { μ | μ < 0 ∧ μ ∈ spectrum_dynamic_leech_inf (L : ℝ) t 0 } = { -μ | μ ∈ zeta_zeros_imag }
