/-
Copyright (c) 2026. Released under Apache 2.0 license.
-/
import Mathlib

/-!
# Klein's icosahedral generators in `PGL₂`

Klein's classical generators of the icosahedral group inside `PGL₂` are written down here
over any field containing a primitive fifth root of unity `z` — in particular over
`ℚ(ζ₅) = ℚ(√5, ζ₅)`, since `(2(z + z⁴) + 1)² = 5` (`ArtinA5Even.Klein.sqrtFive_sq`), so the
golden-ratio quantities are already available.

  `a = ⎡z² 0 ⎤`      `b = ⎡-(z - z⁴)   z² - z³ ⎤`
  `    ⎣0  z³⎦`          `⎣ z² - z³    z - z⁴  ⎦`

The classical normalisation of `b` carries a factor `1/√5`; it is dropped here because a
scalar factor is invisible in `PGL₂`.  What is proved is the icosahedral (2,3,5) presentation
**relations**

  `a⁵ = 1`, `b² = 1`, `(ab)³ = 1`  in `PGL₂(K)`,

together with the exact orders `5`, `2`, `3` of `a`, `b`, `ab`.

## What this is *not*

* It is **not** proved here that `⟨a, b⟩ ≅ A₅`.  The relations above present the `(2,3,5)`
  triangle group, of which the icosahedral group is a quotient; identifying the subgroup
  generated by these two matrices requires an extra argument that is not carried out.
* This is an *abstract* icosahedral embedding.  It is composed with
  `ArtinA5Even.gal1951_equiv_alternating` in `ArtinA5Even/RhoBar1951.lean`, but the resulting
  map is *not* claimed to be the arithmetic representation attached to `f₁₉₅₁`: matching
  conjugacy classes (Frobenius data) is a separate problem, and `Aut(A₅) ≅ S₅`.
* No Maass form, no `L`-function, no automorphy, no `axiom`.
-/

namespace ArtinA5Even

namespace Klein

open Matrix

variable {K : Type*} [Field K]

/-! ## Two elementary lemmas about `2 × 2` matrices -/

/-- Equality of two explicit `2 × 2` matrices, entry by entry. -/
theorem mat2_ext {R : Type*} {a b c d a' b' c' d' : R}
    (h₀₀ : a = a') (h₀₁ : b = b') (h₁₀ : c = c') (h₁₁ : d = d') :
    (!![a, b; c, d] : Matrix (Fin 2) (Fin 2) R) = !![a', b'; c', d'] := by
  subst h₀₀; subst h₀₁; subst h₁₀; subst h₁₁; rfl

/-- A scalar matrix, explicitly. -/
theorem smul_one_fin_two (c : K) :
    (c • (1 : Matrix (Fin 2) (Fin 2) K)) = !![c, 0; 0, c] := by
  rw [Matrix.one_fin_two]
  norm_num [Matrix.smul_of, Matrix.smul_cons]

theorem scalar_eq_smul_one (c : K) : (Matrix.scalar (Fin 2)) c = c • 1 := by
  ext i j
  simp [Matrix.scalar, Matrix.diagonal, Matrix.one_apply]

/-! ## The projective general linear group and its trivial elements -/

/-- `PGL₂(K) = GL₂(K) / centre`. -/
abbrev PGL2 (K : Type*) [Field K] :=
  Matrix.GeneralLinearGroup (Fin 2) K ⧸ Subgroup.center (Matrix.GeneralLinearGroup (Fin 2) K)

/-- The projection `GL₂(K) → PGL₂(K)`. -/
def toPGL2 : Matrix.GeneralLinearGroup (Fin 2) K →* PGL2 K := QuotientGroup.mk' _

/-- A scalar matrix becomes the identity of `PGL₂(K)`. -/
theorem toPGL2_eq_one_of_scalar {g : Matrix.GeneralLinearGroup (Fin 2) K} {c : K}
    (h : (g : Matrix (Fin 2) (Fin 2) K) = c • 1) : toPGL2 g = 1 := by
  rw [toPGL2, QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]
  exact Matrix.GeneralLinearGroup.mem_center_iff_val_mem_range_scalar.mpr
    ⟨c, by rw [scalar_eq_smul_one, h]⟩

/-- An element with a nonzero off-diagonal entry is nontrivial in `PGL₂(K)`. -/
theorem toPGL2_ne_one_of_offdiag {g : Matrix.GeneralLinearGroup (Fin 2) K}
    (h : (g : Matrix (Fin 2) (Fin 2) K) 0 1 ≠ 0) : toPGL2 g ≠ 1 := by
  intro he
  rw [toPGL2, QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff] at he
  obtain ⟨c, hc⟩ := Matrix.GeneralLinearGroup.mem_center_iff_val_mem_range_scalar.mp he
  apply h
  rw [← hc, scalar_eq_smul_one]
  simp

/-- An element whose two diagonal entries differ is nontrivial in `PGL₂(K)`. -/
theorem toPGL2_ne_one_of_diag {g : Matrix.GeneralLinearGroup (Fin 2) K}
    (h : (g : Matrix (Fin 2) (Fin 2) K) 0 0 ≠ (g : Matrix (Fin 2) (Fin 2) K) 1 1) :
    toPGL2 g ≠ 1 := by
  intro he
  rw [toPGL2, QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff] at he
  obtain ⟨c, hc⟩ := Matrix.GeneralLinearGroup.mem_center_iff_val_mem_range_scalar.mp he
  apply h
  rw [← hc, scalar_eq_smul_one]
  simp

/-! ## Consequences of `z⁵ = 1`, `z ≠ 1` -/

variable (z : K)

theorem cyclotomic_rel (hz5 : z ^ 5 = 1) (hz1 : z ≠ 1) : 1 + z + z ^ 2 + z ^ 3 + z ^ 4 = 0 := by
  have h : (z - 1) * (1 + z + z ^ 2 + z ^ 3 + z ^ 4) = 0 := by linear_combination hz5
  rcases mul_eq_zero.mp h with h' | h'
  · exact absurd (sub_eq_zero.mp h') hz1
  · exact h'

theorem z_ne_zero (hz5 : z ^ 5 = 1) : z ≠ 0 := by
  intro h
  rw [h] at hz5
  norm_num at hz5

/-- A field with a primitive fifth root of unity does not have characteristic `5`. -/
theorem five_ne_zero (hz5 : z ^ 5 = 1) (hz1 : z ≠ 1) : (5 : K) ≠ 0 := by
  intro h5
  have h : (z - 1) ^ 5 = 0 := by
    linear_combination hz5 + (-z ^ 4 + 2 * z ^ 3 - 2 * z ^ 2 + z) * h5
  exact hz1 (sub_eq_zero.mp (pow_eq_zero_iff (n := 5) (by norm_num) |>.mp h))

/-- `√5 = 2(z + z⁴) + 1` lies in any field containing a primitive fifth root of unity; in
particular `ℚ(√5, ζ₅) = ℚ(ζ₅)`. -/
theorem sqrtFive_sq (hz5 : z ^ 5 = 1) (hz1 : z ≠ 1) : (2 * (z + z ^ 4) + 1) ^ 2 = 5 := by
  have hc := cyclotomic_rel z hz5 hz1
  linear_combination (8 + 4 * z ^ 3) * hz5 + 4 * hc

/-! ## Klein's generators -/

/-- The matrix of the order-five generator: `diag(z², z³)`. -/
def genAMat : Matrix (Fin 2) (Fin 2) K := !![z ^ 2, 0; 0, z ^ 3]

/-- The matrix of the involution, with Klein's factor `1/√5` omitted (it is invisible in
`PGL₂`). -/
def genBMat : Matrix (Fin 2) (Fin 2) K :=
  !![-(z - z ^ 4), z ^ 2 - z ^ 3; z ^ 2 - z ^ 3, z - z ^ 4]

theorem det_genAMat (hz5 : z ^ 5 = 1) : (genAMat z).det = 1 := by
  rw [genAMat, Matrix.det_fin_two_of]
  linear_combination hz5

theorem det_genBMat (hz5 : z ^ 5 = 1) (hz1 : z ≠ 1) : (genBMat z).det = 5 := by
  have hc := cyclotomic_rel z hz5 hz1
  rw [genBMat, Matrix.det_fin_two_of]
  linear_combination (4 - z - z ^ 3) * hz5 - hc

/-- Klein's order-five generator as an element of `GL₂(K)`. -/
def genA (hz5 : z ^ 5 = 1) : Matrix.GeneralLinearGroup (Fin 2) K :=
  Matrix.GeneralLinearGroup.mkOfDetNeZero (genAMat z) (by rw [det_genAMat z hz5]; norm_num)

/-- Klein's involution as an element of `GL₂(K)`. -/
def genB (hz5 : z ^ 5 = 1) (hz1 : z ≠ 1) : Matrix.GeneralLinearGroup (Fin 2) K :=
  Matrix.GeneralLinearGroup.mkOfDetNeZero (genBMat z)
    (by rw [det_genBMat z hz5 hz1]; exact five_ne_zero z hz5 hz1)

@[simp] theorem val_genA (hz5 : z ^ 5 = 1) :
    ((genA z hz5 : Matrix.GeneralLinearGroup (Fin 2) K) : Matrix (Fin 2) (Fin 2) K)
      = genAMat z := rfl

@[simp] theorem val_genB (hz5 : z ^ 5 = 1) (hz1 : z ≠ 1) :
    ((genB z hz5 hz1 : Matrix.GeneralLinearGroup (Fin 2) K) : Matrix (Fin 2) (Fin 2) K)
      = genBMat z := rfl

/-! ## The three relations, at the matrix level -/

theorem genAMat_pow_five (hz5 : z ^ 5 = 1) : (genAMat z) ^ 5 = 1 := by
  simp only [genAMat, pow_succ, pow_zero, one_mul, Matrix.mul_fin_two, Matrix.one_fin_two]
  refine mat2_ext ?_ ?_ ?_ ?_
  · linear_combination (z ^ 5 + 1) * hz5
  · ring
  · ring
  · linear_combination (z ^ 10 + z ^ 5 + 1) * hz5

theorem genBMat_sq (hz5 : z ^ 5 = 1) (hz1 : z ≠ 1) : (genBMat z) ^ 2 = (-5 : K) • 1 := by
  have hc := cyclotomic_rel z hz5 hz1
  rw [genBMat, sq, Matrix.mul_fin_two, smul_one_fin_two]
  refine mat2_ext ?_ ?_ ?_ ?_
  · linear_combination (z ^ 3 + z - 4) * hz5 + hc
  · ring
  · ring
  · linear_combination (z ^ 3 + z - 4) * hz5 + hc

theorem genABMat_pow_three (hz5 : z ^ 5 = 1) :
    (genAMat z * genBMat z) ^ 3 = (5 * (z - z ^ 4) * (z ^ 2 - z ^ 3)) • 1 := by
  rw [genAMat, genBMat, pow_succ, sq, Matrix.mul_fin_two, Matrix.mul_fin_two,
    Matrix.mul_fin_two, smul_one_fin_two]
  refine mat2_ext ?_ ?_ ?_ ?_
  · linear_combination
      (5 * z ^ 3 - 5 * z ^ 4 - 5 * z ^ 6 + 5 * z ^ 7 + 5 * z ^ 8 - 4 * z ^ 9 - 5 * z ^ 11
        + 4 * z ^ 12) * hz5
  · linear_combination (-z ^ 10 + 2 * z ^ 11 - 2 * z ^ 12 + 2 * z ^ 13 - z ^ 14) * hz5
  · linear_combination (-z ^ 11 + 2 * z ^ 12 - 2 * z ^ 13 + 2 * z ^ 14 - z ^ 15) * hz5
  · linear_combination
      (5 * z ^ 3 - 5 * z ^ 4 - 5 * z ^ 6 + 5 * z ^ 7 + 5 * z ^ 8 - 5 * z ^ 9 - 5 * z ^ 11
        + 5 * z ^ 12 + z ^ 13 - z ^ 16) * hz5

/-! ## The three relations in `PGL₂(K)` -/

/-- Klein's order-five element of `PGL₂(K)`. -/
def kleinA (hz5 : z ^ 5 = 1) : PGL2 K := toPGL2 (genA z hz5)

/-- Klein's involution in `PGL₂(K)`. -/
def kleinB (hz5 : z ^ 5 = 1) (hz1 : z ≠ 1) : PGL2 K := toPGL2 (genB z hz5 hz1)

/-- **`a⁵ = 1`.**  (Already true in `GL₂(K)`.) -/
theorem kleinA_pow_five (hz5 : z ^ 5 = 1) : (kleinA z hz5) ^ 5 = 1 := by
  rw [kleinA, ← map_pow]
  refine toPGL2_eq_one_of_scalar (c := 1) ?_
  rw [Units.val_pow_eq_pow_val, val_genA, genAMat_pow_five z hz5, one_smul]

/-- **`b² = 1`.**  In `GL₂(K)` one has `b² = -5·I`, a nontrivial scalar. -/
theorem kleinB_sq (hz5 : z ^ 5 = 1) (hz1 : z ≠ 1) : (kleinB z hz5 hz1) ^ 2 = 1 := by
  rw [kleinB, ← map_pow]
  refine toPGL2_eq_one_of_scalar (c := -5) ?_
  rw [Units.val_pow_eq_pow_val, val_genB, genBMat_sq z hz5 hz1]

/-- **`(ab)³ = 1`.**  In `GL₂(K)` one has `(ab)³ = 5(z - z⁴)(z² - z³)·I`. -/
theorem kleinAB_pow_three (hz5 : z ^ 5 = 1) (hz1 : z ≠ 1) :
    (kleinA z hz5 * kleinB z hz5 hz1) ^ 3 = 1 := by
  rw [kleinA, kleinB, ← map_mul, ← map_pow]
  refine toPGL2_eq_one_of_scalar (c := 5 * (z - z ^ 4) * (z ^ 2 - z ^ 3)) ?_
  rw [Units.val_pow_eq_pow_val, Units.val_mul, val_genA, val_genB,
    genABMat_pow_three z hz5]

/-! ## Nontriviality, and the exact orders -/

theorem kleinA_ne_one (hz5 : z ^ 5 = 1) (hz1 : z ≠ 1) : kleinA z hz5 ≠ 1 := by
  refine toPGL2_ne_one_of_diag ?_
  rw [val_genA]
  have h00 : (genAMat z) 0 0 = z ^ 2 := rfl
  have h11 : (genAMat z) 1 1 = z ^ 3 := rfl
  rw [h00, h11]
  intro h
  have hz0 := z_ne_zero z hz5
  have : z ^ 2 * (z - 1) = 0 := by linear_combination -h
  rcases mul_eq_zero.mp this with h' | h'
  · exact hz0 (pow_eq_zero_iff (n := 2) (by norm_num) |>.mp h')
  · exact hz1 (sub_eq_zero.mp h')

theorem offdiag_ne_zero (hz5 : z ^ 5 = 1) (hz1 : z ≠ 1) : z ^ 2 - z ^ 3 ≠ 0 := by
  intro h
  have hz0 := z_ne_zero z hz5
  have : z ^ 2 * (1 - z) = 0 := by linear_combination h
  rcases mul_eq_zero.mp this with h' | h'
  · exact hz0 (pow_eq_zero_iff (n := 2) (by norm_num) |>.mp h')
  · exact hz1 (sub_eq_zero.mp h').symm

theorem kleinB_ne_one (hz5 : z ^ 5 = 1) (hz1 : z ≠ 1) : kleinB z hz5 hz1 ≠ 1 := by
  refine toPGL2_ne_one_of_offdiag ?_
  rw [val_genB]
  have h01 : (genBMat z) 0 1 = z ^ 2 - z ^ 3 := rfl
  rw [h01]
  exact offdiag_ne_zero z hz5 hz1

theorem kleinAB_ne_one (hz5 : z ^ 5 = 1) (hz1 : z ≠ 1) :
    kleinA z hz5 * kleinB z hz5 hz1 ≠ 1 := by
  rw [kleinA, kleinB, ← map_mul]
  refine toPGL2_ne_one_of_offdiag ?_
  rw [Units.val_mul, val_genA, val_genB, genAMat, genBMat, Matrix.mul_fin_two]
  have h01 : (!![z ^ 2 * -(z - z ^ 4) + 0 * (z ^ 2 - z ^ 3), z ^ 2 * (z ^ 2 - z ^ 3) + 0 * (z - z ^ 4);
        0 * -(z - z ^ 4) + z ^ 3 * (z ^ 2 - z ^ 3), 0 * (z ^ 2 - z ^ 3) + z ^ 3 * (z - z ^ 4)] :
        Matrix (Fin 2) (Fin 2) K) 0 1 = z ^ 2 * (z ^ 2 - z ^ 3) + 0 * (z - z ^ 4) := rfl
  rw [h01]
  have hz0 := z_ne_zero z hz5
  have h2 : (z : K) ^ 2 ≠ 0 := pow_ne_zero 2 hz0
  intro h
  refine offdiag_ne_zero z hz5 hz1 ?_
  have hmul : z ^ 2 * (z ^ 2 - z ^ 3) = 0 := by linear_combination h
  rcases mul_eq_zero.mp hmul with h' | h'
  · exact absurd h' h2
  · exact h'

theorem orderOf_kleinA (hz5 : z ^ 5 = 1) (hz1 : z ≠ 1) : orderOf (kleinA z hz5) = 5 := by
  haveI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  exact orderOf_eq_prime (kleinA_pow_five z hz5) (kleinA_ne_one z hz5 hz1)

theorem orderOf_kleinB (hz5 : z ^ 5 = 1) (hz1 : z ≠ 1) : orderOf (kleinB z hz5 hz1) = 2 := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  exact orderOf_eq_prime (kleinB_sq z hz5 hz1) (kleinB_ne_one z hz5 hz1)

theorem orderOf_kleinAB (hz5 : z ^ 5 = 1) (hz1 : z ≠ 1) :
    orderOf (kleinA z hz5 * kleinB z hz5 hz1) = 3 := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  exact orderOf_eq_prime (kleinAB_pow_three z hz5 hz1) (kleinAB_ne_one z hz5 hz1)

/-- **The icosahedral `(2,3,5)` relations in `PGL₂(K)`**, for any field `K` containing a
primitive fifth root of unity, together with the exactness of the three orders. -/
theorem klein_icosahedral_relations (hz5 : z ^ 5 = 1) (hz1 : z ≠ 1) :
    (kleinA z hz5) ^ 5 = 1 ∧ (kleinB z hz5 hz1) ^ 2 = 1 ∧
      (kleinA z hz5 * kleinB z hz5 hz1) ^ 3 = 1 ∧
      orderOf (kleinA z hz5) = 5 ∧ orderOf (kleinB z hz5 hz1) = 2 ∧
      orderOf (kleinA z hz5 * kleinB z hz5 hz1) = 3 :=
  ⟨kleinA_pow_five z hz5, kleinB_sq z hz5 hz1, kleinAB_pow_three z hz5 hz1,
    orderOf_kleinA z hz5 hz1, orderOf_kleinB z hz5 hz1, orderOf_kleinAB z hz5 hz1⟩

/-! ## The concrete field `ℚ(√5, ζ₅) = ℚ(ζ₅)` -/

section Cyclotomic

/-- `ζ₅`, a primitive fifth root of unity in `ℚ(ζ₅)`. -/
noncomputable def zeta5 : CyclotomicField 5 ℚ :=
  IsCyclotomicExtension.zeta 5 ℚ (CyclotomicField 5 ℚ)

theorem zeta5_pow_five : zeta5 ^ 5 = 1 :=
  (IsCyclotomicExtension.zeta_spec 5 ℚ (CyclotomicField 5 ℚ)).pow_eq_one

theorem zeta5_ne_one : zeta5 ≠ 1 := by
  intro h1
  have h := (IsCyclotomicExtension.zeta_spec 5 ℚ (CyclotomicField 5 ℚ)).eq_orderOf
  rw [zeta5] at h1
  rw [h1] at h
  simp at h

/-- `√5 ∈ ℚ(ζ₅)`: the field `ℚ(√5, ζ₅)` of Klein's generators is just `ℚ(ζ₅)`. -/
theorem sqrtFive_sq_cyclotomic : (2 * (zeta5 + zeta5 ^ 4) + 1) ^ 2 = 5 :=
  sqrtFive_sq zeta5 zeta5_pow_five zeta5_ne_one

/-- **Klein's icosahedral generators over `ℚ(√5, ζ₅) = ℚ(ζ₅)`**: two elements of
`PGL₂(ℚ(ζ₅))` of orders `5` and `2` whose product has order `3`. -/
theorem klein_icosahedral_relations_cyclotomic :
    (kleinA zeta5 zeta5_pow_five) ^ 5 = 1 ∧
      (kleinB zeta5 zeta5_pow_five zeta5_ne_one) ^ 2 = 1 ∧
      (kleinA zeta5 zeta5_pow_five * kleinB zeta5 zeta5_pow_five zeta5_ne_one) ^ 3 = 1 ∧
      orderOf (kleinA zeta5 zeta5_pow_five) = 5 ∧
      orderOf (kleinB zeta5 zeta5_pow_five zeta5_ne_one) = 2 ∧
      orderOf (kleinA zeta5 zeta5_pow_five * kleinB zeta5 zeta5_pow_five zeta5_ne_one) = 3 :=
  klein_icosahedral_relations zeta5 zeta5_pow_five zeta5_ne_one

end Cyclotomic

end Klein

end ArtinA5Even
