/-
Copyright (c) 2026 SOLFUNMEME contributors. Released under Apache 2.0.
-/
import RequestProject.Solfunmeme.Tickets.Queries

/-!
# The implementation plan, as data

Generated by `scripts/codeberg_plan.py`; the rules that produce it are
documented there and in `PLAN.md`. Do not edit by hand.

Each entry is `(ticket, phase, prerequisites)`; there are 105 of
them, one for every item on the wish list, in the order the plan proposes
to do them in. What the entries have to satisfy — and the machine-checked
proof that they do — is in `RequestProject/Tickets/Plan.lean`.
-/

namespace SFM.Tickets

/-- The plan: `(ticket, phase, prerequisites)` in the proposed order. -/
def planRaw : List (Nat × Nat × List Nat) :=
  [(5, 1, [])
  , (39, 1, [])
  , (182, 1, [])
  , (18, 1, [])
  , (10, 2, [])
  , (86, 2, [])
  , (29, 2, [])
  , (78, 2, [])
  , (125, 2, [])
  , (85, 2, [])
  , (36, 2, [])
  , (40, 2, [])
  , (107, 2, [])
  , (153, 2, [])
  , (176, 2, [])
  , (94, 3, [])
  , (23, 3, [])
  , (62, 3, [])
  , (164, 3, [])
  , (172, 3, [])
  , (192, 3, [])
  , (19, 3, [])
  , (96, 3, [])
  , (11, 3, [])
  , (24, 3, [])
  , (27, 3, [])
  , (35, 3, [])
  , (41, 3, [])
  , (55, 3, [])
  , (77, 3, [])
  , (87, 3, [])
  , (95, 3, [])
  , (98, 3, [])
  , (100, 3, [])
  , (143, 3, [])
  , (159, 3, [])
  , (215, 3, [])
  , (44, 4, [])
  , (114, 4, [])
  , (123, 4, [])
  , (174, 4, [])
  , (3, 4, [])
  , (71, 4, [])
  , (126, 4, [])
  , (76, 4, [])
  , (138, 4, [])
  , (188, 4, [])
  , (227, 4, [])
  , (33, 4, [])
  , (32, 4, [])
  , (34, 4, [])
  , (99, 4, [])
  , (116, 4, [])
  , (119, 4, [])
  , (151, 4, [])
  , (191, 4, [])
  , (228, 4, [])
  , (42, 5, [])
  , (43, 5, [])
  , (17, 5, [])
  , (20, 5, [])
  , (80, 5, [])
  , (89, 5, [])
  , (148, 5, [])
  , (189, 5, [])
  , (69, 5, [])
  , (101, 5, [])
  , (4, 5, [])
  , (52, 5, [])
  , (131, 5, [])
  , (145, 5, [])
  , (158, 5, [])
  , (165, 5, [])
  , (166, 5, [])
  , (168, 5, [])
  , (171, 5, [])
  , (175, 5, [])
  , (178, 5, [])
  , (196, 5, [])
  , (205, 5, [])
  , (207, 5, [])
  , (221, 5, [])
  , (226, 5, [])
  , (48, 5, [])
  , (50, 5, [])
  , (6, 5, [])
  , (14, 5, [])
  , (25, 5, [])
  , (28, 5, [])
  , (46, 5, [])
  , (79, 5, [])
  , (97, 5, [])
  , (120, 5, [])
  , (133, 5, [])
  , (149, 5, [])
  , (157, 5, [])
  , (160, 5, [])
  , (161, 5, [])
  , (162, 5, [])
  , (170, 5, [])
  , (193, 5, [])
  , (203, 5, [])
  , (230, 5, [])
  , (31, 6, [10])
  , (186, 6, [182])
  ]

/-- The phases of the plan, with the name of each. -/
def planPhases : List (Nat × String) :=
  [(1, "In flight")
  , (2, "Paid")
  , (3, "Quick wins")
  , (4, "Main build")
  , (5, "Shape first")
  , (6, "After others")
  ]

end SFM.Tickets
