-- GENERATED by scripts/index_facts.py -- do not edit by hand.
-- Source: data/index/chunks/*.received.json

import RequestProject.Solfunmeme.IndexFeed.DataPart0
import RequestProject.Solfunmeme.IndexFeed.DataPart1
import RequestProject.Solfunmeme.IndexFeed.DataPart2
import RequestProject.Solfunmeme.IndexFeed.DataPart3
import RequestProject.Solfunmeme.IndexFeed.DataPart4
import RequestProject.Solfunmeme.IndexFeed.DataPart5

namespace Solfunmeme.IndexFeed

/-- The index feed as received: every `*.received.json` chunk under
`data/index/chunks`, ordered by sequence number. -/
def feed : List RawChunk :=
  part0 ++ part1 ++ part2 ++ part3 ++ part4 ++ part5

/-- The feed length announced by the chunks' `total` field. -/
def announcedTotal : Nat := 664

/-- The path prefix shared by every indexed document. -/
def corpusPrefix : String := "83dc98fa-c1b1-41f6-96df-ef863afcf816_aristotle/output-final_aristotle/.lake/packages/"

end Solfunmeme.IndexFeed
