import RequestProject.Solfunmeme.IndexFeed.Data

/-!
# What the received index feed actually contains

Every theorem in this file is a statement about `feed`, the transcription of
the chunks dumped under `data/index/chunks/*.received.json`
(`RequestProject/IndexFeed/Data.lean`, generated by `scripts/index_facts.py`).

The counting facts are finite checks.  Those over document ids and sequence
numbers are checked by the kernel (`decide`, `rfl`); those that compare the
52543 posting terms or the 2250 document paths are far too slow for the kernel
and are checked by evaluating the same decision procedure with the compiler
(`native_decide`), which additionally rests on `Lean.ofReduceBool` and
`Lean.trustCompiler`.  The structural results they are combined with come from
`RequestProject/IndexFeed/Model.lean` and are kernel-checked.
`RequestProject/IndexFeed/AxiomAudit.lean` prints both groups.
-/

namespace Solfunmeme.IndexFeed

set_option maxRecDepth 400000
set_option maxHeartbeats 4000000

/-- The chunks that carried a payload (documents or postings). -/
def payloadFeed : List RawChunk := feed.filter fun c => c.hasPayload

/-- The size of the document block a chunk of this feed delivers. -/
def blockSize : Nat := 50

/-! ## The shape of the feed -/

/-- 46 chunk messages were received. -/
theorem feed_length : feed.length = 46 := by rfl

/-- Their sequence numbers, in order. -/
theorem feed_seqs :
    seqs feed =
      [319, 320, 321, 322, 324, 325, 327, 328, 329, 330, 336, 341, 346, 349, 352,
       355, 357, 360, 362, 365, 369, 374, 377, 379, 382, 384, 385, 387, 389, 391,
       394, 397, 400, 402, 405, 407, 409, 412, 416, 418, 422, 425, 428, 432, 435,
       1501751] := by
  rfl

/-- No sequence number was delivered twice. -/
theorem feed_seqs_nodup : (seqs feed).Nodup := by decide

/-- 45 of the 46 messages carried a payload. -/
theorem payloadFeed_length : payloadFeed.length = 45 := by decide

/-- The one payload-free message is chunk 1501751, the by-reference chunk from
the global dedup store: it announces `theorem` content but carries no
documents, no postings and no digest. -/
theorem empty_chunk_is_1501751 :
    seqs (feed.filter fun c => !c.hasPayload) = [1501751] := by decide

/-- The feed announces 664 chunks. -/
theorem announced_total_eq : announcedTotal = 664 := rfl

/-- That one sequence number lies far beyond the length the feed announces for
itself, so it cannot be a position in the feed at all. -/
theorem chunk_1501751_beyond_announced : announcedTotal < 1501751 := by
  norm_num [announcedTotal]

/-- 619 of the 664 announced chunks have never arrived. -/
theorem missing_length : (missing feed announcedTotal).length = 619 := by decide

/-- Nothing was delivered before chunk 319 or after chunk 435, apart from the
payload-free chunk 1501751. -/
theorem delivered_range :
    ∀ s ∈ seqs feed, s = 1501751 ∨ (319 ≤ s ∧ s ≤ 435) := by
  have h : (seqs feed).all (fun s => decide (s = 1501751 ∨ (319 ≤ s ∧ s ≤ 435))) = true := by
    decide
  exact fun s hs => of_decide_eq_true (List.all_eq_true.1 h s hs)

/-! ## The documents -/

/-- Each payload chunk carries the block of 50 consecutive document ids that
its sequence number determines: chunk `s` carries ids `50·(s-1) … 50·s-1`. -/
theorem payload_blocks_ok :
    ∀ c ∈ payloadFeed, RawChunk.blockOK blockSize c = true := by
  have h : payloadFeed.all (fun c => RawChunk.blockOK blockSize c) = true := by decide
  exact fun c hc => List.all_eq_true.1 h c hc

/-- Every payload chunk has a positive sequence number. -/
theorem payload_seq_pos : ∀ c ∈ payloadFeed, 0 < c.seq := by
  have h : payloadFeed.all (fun c => decide (0 < c.seq)) = true := by decide
  exact fun c hc => of_decide_eq_true (List.all_eq_true.1 h c hc)

/-- Sequence numbers of the payload chunks are distinct. -/
theorem payloadFeed_seqs_nodup : (seqs payloadFeed).Nodup := by decide

/-- The payload-free chunk contributes nothing, so the feed's documents are
exactly the documents of its payload chunks. -/
theorem docIds_eq_payload : docIds payloadFeed = docIds feed :=
  docIds_filter_hasPayload feed

/-- 2250 documents have been delivered. -/
theorem docs_count : (allDocs feed).length = 2250 := by rfl

/-- No document is delivered twice — a consequence of the block structure,
not of a separate count. -/
theorem docIds_nodup : (docIds feed).Nodup := by
  rw [← docIds_eq_payload]
  exact docIds_nodup_of_blocks payloadFeed blockSize payload_blocks_ok
    payloadFeed_seqs_nodup payload_seq_pos

/-- The delivered documents are 2250 distinct files. -/
theorem paths_nodup : ((allDocs feed).map Doc.path).Nodup := by native_decide

/-! ## The postings -/

/-- 52543 postings have been delivered. -/
theorem postings_count : (allPostings feed).length = 52543 := by rfl

/-- Every posting refers to a document of the chunk that carries it. -/
theorem chunks_self_contained :
    ∀ c ∈ feed, RawChunk.selfContained c = true := by
  have h : feed.all (fun c => RawChunk.selfContained c) = true := by native_decide
  exact fun c hc => List.all_eq_true.1 h c hc

/-- Within a chunk, no posting is repeated. -/
theorem chunk_postings_nodup : ∀ c ∈ payloadFeed, c.postings.Nodup := by
  have h : payloadFeed.all (fun c => decide c.postings.Nodup) = true := by native_decide
  exact fun c hc => of_decide_eq_true (List.all_eq_true.1 h c hc)

/-- The postings of the feed are those of its payload chunks. -/
theorem allPostings_eq_payload : allPostings payloadFeed = allPostings feed :=
  allPostings_filter_hasPayload feed

/-- No posting is delivered twice: every one of the 52543 postings is a
distinct (document, term) pair.  This follows from the per-chunk checks and
the disjointness of the document blocks. -/
theorem postings_nodup : (allPostings feed).Nodup := by
  rw [← allPostings_eq_payload]
  refine allPostings_nodup_of_blocks payloadFeed blockSize payload_blocks_ok
    payloadFeed_seqs_nodup payload_seq_pos ?_ chunk_postings_nodup
  intro c hc
  exact chunks_self_contained c (List.mem_of_mem_filter hc)

/-- 195 of the 2250 delivered documents carry no posting at all. -/
theorem docs_without_postings_count : docsWithoutPostings feed = 195 := by native_decide

/-- The index knows 38627 distinct terms. -/
theorem term_count : termCount feed = 38627 := by native_decide

/-- 35864 of them occur in exactly one posting. -/
theorem hapax_count : hapaxCount feed = 35864 := by native_decide

/-- The three most frequent terms are the Lean declaration keywords. -/
theorem docFreq_def : docFreq feed "def" = 1378 := by native_decide

theorem docFreq_theorem : docFreq feed "theorem" = 1245 := by native_decide

theorem docFreq_lemma : docFreq feed "lemma" = 1072 := by native_decide

/-! ## What corpus the index is over -/

/-- Every delivered document sits under one Aristotle run's build directory
(`corpusPrefix`), not in the dataset under review. -/
theorem all_docs_under_corpus_prefix :
    ∀ d ∈ allDocs feed, corpusPrefix.isPrefixOf d.path = true := by
  have h : (allDocs feed).all (fun d => corpusPrefix.isPrefixOf d.path) = true := by
    native_decide
  exact fun d hd => List.all_eq_true.1 h d hd

/-- 2050 of the documents are Mathlib sources. -/
theorem mathlib_docs : packageDocs feed corpusPrefix "mathlib" = 2050 := by native_decide

/-- 200 are Aesop sources. -/
theorem aesop_docs : packageDocs feed corpusPrefix "aesop" = 200 := by native_decide

/-- Those two packages exhaust the delivered documents. -/
theorem packages_exhaust_docs :
    packageDocs feed corpusPrefix "mathlib" + packageDocs feed corpusPrefix "aesop"
      = (allDocs feed).length := by
  rw [mathlib_docs, aesop_docs, docs_count]

/-- Nothing in the delivered index comes from the dataset under review: no
document path mentions the dataset. -/
theorem no_solfunmeme_document :
    ∀ d ∈ allDocs feed, (d.path.splitOn "solfunmeme").length = 1 := by
  have h : (allDocs feed).all (fun d => decide ((d.path.splitOn "solfunmeme").length = 1))
      = true := by native_decide
  exact fun d hd => of_decide_eq_true (List.all_eq_true.1 h d hd)

/-- … and no indexed term mentions it either. -/
theorem no_solfunmeme_term :
    ∀ p ∈ allPostings feed, (p.term.splitOn "solfunmeme").length = 1 := by
  have h : (allPostings feed).all
      (fun p => decide ((p.term.splitOn "solfunmeme").length = 1)) = true := by native_decide
  exact fun p hp => of_decide_eq_true (List.all_eq_true.1 h p hp)

/-- So the query the review would start from returns nothing. -/
theorem solfunmeme_no_hits : hits feed "solfunmeme" = [] := by native_decide

end Solfunmeme.IndexFeed
