import RequestProject.Solfunmeme.Onchain.Dataset

/-!
# The ingested JSON-RPC captures, transcribed into Lean

**Generated by `scripts/onchain_facts.py` — do not edit by hand.**
`python3 scripts/onchain_facts.py --check` fails if this file drifts from the
captures shipped in `dataset/` and `fixtures/`, so the theorems in
`RequestProject.Onchain.CaptureFacts` are theorems about those bytes.

* `dataset/` holds **real** captures of the SOLFUNMEME mint.
* `fixtures/` holds **synthetic**, hand-written responses; every fact below that
  mentions a fixture is a fact about those made-up numbers, not about the chain.
-/

namespace Solana.Captures

open Solana.Dataset
open Solana.Holders

/-- The mint the whole corpus is about. -/
def mint : String := "BwUTq7fS6sfUmHDwAiCQZ3asSiPEapW5zDrsbwtapump"

/-- Every capture file shipped in `dataset/` (the real ones). -/
def datasetFiles : List String :=
  [
    "method_getAccountInfo_address_BwUTq7fS6sfUmHDwAiCQZ3asSiPEapW5zDrsbwtapump_15584805420125613375.json",
    "method_getSignaturesForAddress_address_BwUTq7fS6sfUmHDwAiCQZ3asSiPEapW5zDrsbwtapump_1.json" ]

/-- Every capture file shipped in `fixtures/` (the synthetic ones). -/
def fixtureFiles : List String :=
  [
    "method_getMultipleAccounts_addresses_2625650183996368760_1.json",
    "method_getTokenLargestAccounts_address_BwUTq7fS6sfUmHDwAiCQZ3asSiPEapW5zDrsbwtapump_1.json",
    "method_getTokenSupply_address_BwUTq7fS6sfUmHDwAiCQZ3asSiPEapW5zDrsbwtapump_1.json" ]

/-! ## The real `getAccountInfo` capture on the mint account -/

/-- Decimals of the mint, from the real capture. -/
def realDecimals : Nat := 6

/-- Raw supply of the mint, from the real capture. -/
def realSupply : Nat := 999906030213118

/-- Program owning the mint account, from the real capture. -/
def realOwnerProgram : String := "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

/-- Mint authority reported by the real capture (`none` = JSON `null`). -/
def realMintAuthority : Option String := none

/-- Freeze authority reported by the real capture (`none` = JSON `null`). -/
def realFreezeAuthority : Option String := none

/-- Context slot of the real capture. -/
def realSlot : Nat := 336594291

/-- Validator API version that answered the real capture. -/
def realApiVersion : String := "2.1.21"

/-! ## The real `getSignaturesForAddress` capture (a 5-record excerpt) -/

/-- The signature records shipped in `dataset/`. -/
def realSignatures : List SignatureRecord :=
  [
    { signature := "35hVTDhmox7XqDqRmDvg6N1WSFgeXVnSpVXjbNzuyb9FMPzTFpySZMkLZrCYCvdrkKh1bGmbnmDPyypmYmzgMVsN",
      slot := 314266537, blockTime := some 1736991372,
      memo := none, failed := true },
    { signature := "4bcKJzYzLeRuPPt9B4AhprZUnjakUaaWAFjUDRD9TJa9UzunuszieJkZDjqbA7njDM7NBiNDCyYLAM8sEGseqHa4",
      slot := 314266537, blockTime := some 1736991372,
      memo := none, failed := true },
    { signature := "4R88CrVy5cnfPbkntkWxt8CFNnKz3v3uzF6SQVFbAgaaxHr9SHh4iMzFSngMTjv1u515fJDGq5KeJzRetfgydq4X",
      slot := 314266536, blockTime := some 1736991371,
      memo := none, failed := false },
    { signature := "5vVYkVHrDwdpDNv1irFgqTp2ozddMpJwhq5dZdaVBwxx1sPD6jNPFfu7x4hUe8TSZoPaUohN62vP7NM4rNposYgD",
      slot := 314266535, blockTime := some 1736991371,
      memo := some "[3] FRA", failed := true },
    { signature := "25V7PnMF3PK1QKFKoWYKFzL8MrrEq8ejZmK4vsiHntsZt1pnaHtbUNGKKpC2Q2msFi4og18Aq8TvN7iDDJiBxgeK",
      slot := 314266534, blockTime := some 1736991371,
      memo := some "[36] 05799ce7-b522-4a7a-9c3a-3ce8af27f656", failed := false } ]

/-! ## The synthetic `fixtures/` corpus -/

/-- Decimals in the synthetic `getTokenSupply` fixture. -/
def fixtureDecimals : Nat := 6

/-- Raw supply in the synthetic `getTokenSupply` fixture. -/
def fixtureSupply : Nat := 999805262437066

/-- The synthetic token accounts, each already carrying the wallet that the
synthetic `getMultipleAccounts` fixture names as its owner. -/
def fixtureAccounts : List TokenAccountBalance :=
  [
    { address := "9KDwgnUe4GAbFWjQGg5xJL4dtiW5iiuesWPjFEXgz6M",
      owner := some "HMEKzpgzJEfyYyqoob5uGHR9P3LF6248zbm8tWgaApim", amount := 150000000000000 },
    { address := "ckHwo3Yn9LMgif8nfLDi31hUTqtBDMXnkowBMQ5Kiak",
      owner := some "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1", amount := 90000000000000 },
    { address := "26BMwuJcvEQwfMQgqkcekAR3BaKHtfAGgtVWkX6jkRgs",
      owner := some "7GgPYjS5Dza89wV6FpZ23kUJRG5vbQ1GM25ezspYFSoE", amount := 60000000000000 },
    { address := "2ZcRx1Zh4KVXdzAEtqu5nHpNtgnhc6y1bkA7ABQvykwp",
      owner := some "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1", amount := 45000000000000 },
    { address := "333Vx7pmCQa7ccunwwBWpRDiboG7KYmkWbphZqj8D6Cm",
      owner := some "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R", amount := 30000000000000 },
    { address := "3WUZxE5qLTuhkrX6BiFfYdMGKAbDRzs26zWgJjbY2L5A",
      owner := some "8HoQnePLqPj4M7PUDzfw8e3Ymdwgc7NLGnaTUapubyvu", amount := 10000000000000 } ]

/-- The wallets those accounts belong to, merged and sorted by balance: what the
ingestion pipeline is expected to produce from `fixtures/`. -/
def fixtureHolders : List Holder :=
  [
    { address := "HMEKzpgzJEfyYyqoob5uGHR9P3LF6248zbm8tWgaApim", amount := 150000000000000 },
    { address := "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1", amount := 135000000000000 },
    { address := "7GgPYjS5Dza89wV6FpZ23kUJRG5vbQ1GM25ezspYFSoE", amount := 60000000000000 },
    { address := "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R", amount := 30000000000000 },
    { address := "8HoQnePLqPj4M7PUDzfw8e3Ymdwgc7NLGnaTUapubyvu", amount := 10000000000000 } ]

end Solana.Captures
