import RequestProject.Gvcs.Printer.Render

/-!
# The print-job writer

`lake exe printer [dir]` writes the self-print job of
`RequestProject/Printer/SelfPrint.lean` out of the Lean development:

* `selfprint.gcode` — the printer's own plastic parts as G-code, produced from
  the very list of instructions the interpreter executes in `selfPrint`;
* `deposited.json` — the voxels that interpreter says are left on the bed;
* `selfprint-NN.svg` — the bed at each eighth of the job, drawn from the
  toolpath;
* `selfprint.svg` — the same frames animated, bare bed to finished plate;
* `index.html` — a page showing them;
* `README.md` — how to check the G-code against the model.

The default directory is `printer`.  `tools/check_gcode.py` re-simulates the
emitted text and compares the result with `deposited.json`.
-/

open LifeTrac Printer

/-- The job the executable writes: the printer's own parts. -/
def selfPrintJob : List Instr := job d3d 205 printerParts

/-- The note that goes with the generated files. -/
def printerReadme : String :=
  "# The printer printing its own parts\n\n" ++
  "Everything in this directory is generated by `lake exe printer` from the\n" ++
  "Lean development.  Do not edit it by hand.\n\n" ++
  "## What it is\n\n" ++
  "`selfprint.gcode` is the print job for the six plastic parts of the printer\n" ++
  "itself — two Z-motor mounts, the X carriage, a belt clamp, the spool holder\n" ++
  "and the fan duct — as modelled in `RequestProject/Printer/SelfPrint.lean`.\n" ++
  "The toolpath is produced by the slicer of `RequestProject/Printer/Slice.lean`\n" ++
  "and is the same list of instructions the Lean interpreter executes in the\n" ++
  "theorem `selfPrint`: the job runs with no fault, lays down 908 cells of\n" ++
  "filament, and takes 3835 ticks.  One cell is 10 mm and one tick a second.\n\n" ++
  "`deposited.json` is the set of cells the interpreter leaves on the bed.\n\n" ++
  "## Checking it\n\n" ++
  "```\n" ++
  "python3 tools/check_gcode.py printer/selfprint.gcode printer/deposited.json\n" ++
  "```\n\n" ++
  "The script simulates the G-code independently — homing, heating, cold\n" ++
  "extrusion, the build volume, collisions and mid-air extrusion — and checks\n" ++
  "that the material it ends up with is exactly the set in `deposited.json`.\n\n" ++
  "## Pictures\n\n" ++
  "`selfprint-NN.svg` is the bed after each eighth of the job and\n" ++
  "`selfprint.svg` animates them; both are drawn from the toolpath itself, so\n" ++
  "they show the same print the theorems are about.  `index.html` collects\n" ++
  "them.\n"

/-- Two-digit frame number, for file names. -/
def pad2 (k : ℕ) : String :=
  let s := toString k
  if s.length ≥ 2 then s else "0" ++ s

/-- The page that shows the frames. -/
def printerGallery : String :=
  let frame := fun (i : ℕ) (k : ℕ) =>
    "<h2>" ++ toString k ++ " of " ++ toString selfPath.length ++ " cells</h2>\n" ++
      "<img src=\"selfprint-" ++ pad2 i ++ ".svg\" alt=\"the bed after " ++
      toString k ++ " cells\">\n"
  "<!doctype html>\n<html lang=\"en\"><head><meta charset=\"utf-8\">\n" ++
  "<title>The printer printing its own parts</title>\n" ++
  "<style>body{background:#0e1512;color:#e7f0e9;font-family:system-ui,sans-serif;" ++
  "margin:0 auto;max-width:1100px;padding:24px}h1{color:#79c98a}" ++
  "h2{color:#e8c46a;border-bottom:1px solid #2b3a31;padding-bottom:4px;margin-top:36px}" ++
  "img{max-width:100%;border:1px solid #2b3a31;border-radius:6px}" ++
  "p{color:#8fa697}code{color:#cfe6d6}</style>\n" ++
  "</head><body>\n<h1>The printer printing its own parts</h1>\n" ++
  "<p>Every picture here is drawn by <code>lake exe printer</code> from the toolpath " ++
  "the Lean interpreter executes in <code>RequestProject/Printer/SelfPrint.lean</code>. " ++
  "The job runs with no fault, lays down 908 cells of filament and takes 3835 ticks.</p>\n" ++
  "<h2>The whole print</h2>\n" ++
  "<img src=\"selfprint.svg\" alt=\"the print, from bare bed to finished plate\">\n" ++
  String.join (frameSteps.zipIdx.map fun (k, i) => frame i k) ++
  "</body></html>\n"

/-- Write the job out. -/
def main (args : List String) : IO Unit := do
  let dir := args.headD "printer"
  IO.FS.createDirAll dir
  IO.FS.writeFile (dir ++ "/selfprint.gcode")
    (gcode "the printer's own plastic parts" selfPrintJob)
  IO.println s!"wrote {dir}/selfprint.gcode"
  IO.FS.writeFile (dir ++ "/deposited.json") (depositedJson (enum d3d.env printerParts))
  IO.println s!"wrote {dir}/deposited.json"
  for (k, i) in frameSteps.zipIdx do
    let name := dir ++ "/selfprint-" ++ pad2 i ++ ".svg"
    IO.FS.writeFile name (frameSvg k)
    IO.println s!"wrote {name}"
  IO.FS.writeFile (dir ++ "/selfprint.svg") progressSvg
  IO.println s!"wrote {dir}/selfprint.svg"
  IO.FS.writeFile (dir ++ "/index.html") printerGallery
  IO.println s!"wrote {dir}/index.html"
  IO.FS.writeFile (dir ++ "/README.md") printerReadme
  IO.println s!"wrote {dir}/README.md"
