import RequestProject.Gvcs.Voxel.Render

/-!
# The voxel extractor

`lake exe voxel [dir]` writes the voxel model of the machine out of the Lean
development:

* `LifeTracVoxel.lua` — the Roblox module, one part per run of voxels, built
  from the Lua syntax tree of `RequestProject/Voxel/Lua.lean`;
* `occupancy.json` — the occupied voxels of every keyframe, computed straight
  from the occupancy functions, for `tools/check_roblox_lua.py` to compare the
  Lua against;
* `lifetrac-lift-NN.svg` — an isometric picture of the machine at each
  keyframe, drawn from the same functions;
* `lifetrac-lift-cycle.svg` — those keyframes animated into one lift cycle;
* `README.md` — how to load the module in Roblox Studio.

The default directory is `roblox`.
-/

open LifeTrac Voxel

/-- The note that goes with the generated module. -/
def robloxReadme : String :=
  "# LifeTrac, as voxels, in Roblox\n\n" ++
  "Everything in this directory is generated by `lake exe voxel` from the Lean\n" ++
  "development.  Do not edit it by hand.\n\n" ++
  "## What the model is\n\n" ++
  "Each part of the machine is a function from a point of the integer lattice to\n" ++
  "a bit — \"is there material here?\" — and the machine is the union of those\n" ++
  "functions (`RequestProject/Voxel/Parts.lean`).  One voxel is 5 cm.  The parts\n" ++
  "that move are functions of the loader lift as well, so the geometry below is\n" ++
  "given at the lift commands in `M.LIFTS`.\n\n" ++
  "`RequestProject/Voxel/Bricks.lean` compiles each part into maximal runs of\n" ++
  "voxels along `x`, and proves that the runs cover exactly the occupied voxels\n" ++
  "of the window (`bricksOf_correct`), so the parts you see in Roblox are the\n" ++
  "solid the proofs are about.\n\n" ++
  "## Using it\n\n" ++
  "```lua\n" ++
  "local LifeTrac = require(script.LifeTracVoxel)\n" ++
  "LifeTrac.build(workspace, 1)        -- loader down\n" ++
  "LifeTrac.build(workspace, #LifeTrac.LIFTS)  -- loader up\n" ++
  "```\n\n" ++
  "`M.build(parent, frame)` creates one `Model` per body, and one anchored\n" ++
  "`Part` per brick, `M.VOXEL` studs to the voxel.  Lean `(x, y, z)` becomes\n" ++
  "Roblox `(x, z, -y)`, because Roblox has `Y` up.\n\n" ++
  "## Files\n\n" ++
  "* `LifeTracVoxel.lua` — the module;\n" ++
  "* `occupancy.json` — the occupied voxels of each keyframe, straight from the\n" ++
  "  Lean occupancy functions;\n" ++
  "* `lifetrac-lift-NN.svg` — isometric pictures of the keyframes;\n" ++
  "* `lifetrac-lift-cycle.svg` — the same keyframes, animated into a lift\n" ++
  "  cycle;\n" ++
  "* `index.html` — a page showing all of them;\n" ++
  "* `tools/check_roblox_lua.py` — runs the module against a stub of the Roblox\n" ++
  "  API and checks that the parts it creates occupy exactly the voxels in\n" ++
  "  `occupancy.json`.\n"

/-- Two-digit lift number, for file names. -/
def pad2Lift (n : Int) : String :=
  if n < 10 then "0" ++ toString n else toString n

/-- A gallery page for the pictures, so the keyframes and the lift cycle can be
looked at in a browser. -/
def robloxGallery : String :=
  let frame := fun (l : Int) =>
    "<h2>Lift " ++ toString l ++ " of " ++ toString liftMax ++ "</h2>\n" ++
      "<img src=\"lifetrac-lift-" ++ pad2Lift l ++ ".svg\" alt=\"the machine at lift " ++
      toString l ++ "\">\n"
  "<!doctype html>\n<html lang=\"en\"><head><meta charset=\"utf-8\">\n" ++
  "<title>LifeTrac \u00b7 the voxel model</title>\n" ++
  "<style>body{background:#0e1512;color:#e7f0e9;font-family:system-ui,sans-serif;" ++
  "margin:0 auto;max-width:1100px;padding:24px}h1{color:#79c98a}" ++
  "h2{color:#e8c46a;border-bottom:1px solid #2b3a31;padding-bottom:4px;margin-top:36px}" ++
  "img{max-width:100%;border:1px solid #2b3a31;border-radius:6px}" ++
  "p{color:#8fa697}a{color:#6fb7e8}code{color:#cfe6d6}</style>\n" ++
  "</head><body>\n<h1>LifeTrac \u00b7 the voxel model</h1>\n" ++
  "<p>Every picture here is drawn by <code>lake exe voxel</code> from the occupancy " ++
  "functions of <code>RequestProject/Voxel/Parts.lean</code> \u2014 one voxel is 5 cm, and a " ++
  "part is the function that says where its material is.  The same functions are " ++
  "compiled into <a href=\"LifeTracVoxel.lua\">LifeTracVoxel.lua</a> for Roblox.</p>\n" ++
  "<h2>The lift cycle</h2>\n" ++
  "<img src=\"lifetrac-lift-cycle.svg\" alt=\"the loader going up and down\">\n" ++
  String.join (keyLifts.map frame) ++
  "</body></html>\n"

/-- Write the model out. -/
def main (args : List String) : IO Unit := do
  let dir := args.headD "roblox"
  IO.FS.createDirAll dir
  IO.FS.writeFile (dir ++ "/LifeTracVoxel.lua") machineLua
  IO.println s!"wrote {dir}/LifeTracVoxel.lua"
  IO.FS.writeFile (dir ++ "/occupancy.json") occupancyJson
  IO.println s!"wrote {dir}/occupancy.json"
  for l in keyLifts do
    let name := dir ++ "/lifetrac-lift-" ++ pad2Lift l ++ ".svg"
    IO.FS.writeFile name (isoSvg l)
    IO.println s!"wrote {name}"
  IO.FS.writeFile (dir ++ "/lifetrac-lift-cycle.svg") isoAnimSvg
  IO.println s!"wrote {dir}/lifetrac-lift-cycle.svg"
  IO.FS.writeFile (dir ++ "/index.html") robloxGallery
  IO.println s!"wrote {dir}/index.html"
  IO.FS.writeFile (dir ++ "/README.md") robloxReadme
  IO.println s!"wrote {dir}/README.md"
